export const Document = [
  //ARG
  //Corpus

  { id: 23, src: "corpus/ARG/02ESARGTOFOCCVV" },
  { id: 24, src: "corpus/ARG/03ESARGTOFOCCVV" },
  { id: 25, src: "corpus/ARG/04ESARGTOFOCCVV" },
  { id: 26, src: "corpus/ARG/05ESARGTOFOCCVV" },
  { id: 27, src: "corpus/ARG/06ESARGTOFOCCVV" },
  { id: 28, src: "corpus/ARG/07ESARGTOFOCCVV" },
  { id: 29, src: "corpus/ARG/08ESARGTOFOCCVV" },
  { id: 30, src: "corpus/ARG/09ESARGTOFOCCVV" },
  { id: 31, src: "corpus/ARG/10ESARGTOTXTCCVV" },
  { id: 32, src: "corpus/ARG/11ESARGTOFOCCVV" },
  { id: 23, src: "corpus/ARG/12ESARGTOFOCCVV" },
  { id: 24, src: "corpus/ARG/13ESARGTOFOCCVV" },
  { id: 25, src: "corpus/ARG/14ESARGTOFOCCVV" },
  { id: 26, src: "corpus/ARG/19ESARGTOFOCCVV" },
  { id: 27, src: "corpus/ARG/20ESARGTOFOCCVV" },
  { id: 28, src: "corpus/ARG/21ESARGTOFOCCVV" },
  { id: 29, src: "corpus/ARG/24ESARGTOFOCCVV" },
  { id: 30, src: "corpus/ARG/28ESARGTOFOCCVV" },
  { id: 31, src: "corpus/ARG/30ESARGTOFOCCVV" },
  { id: 32, src: "corpus/ARG/32ESARGTOFOCCVV" },
  { id: 27, src: "corpus/ARG/33ESARGTOFOCCVV" },
  { id: 28, src: "corpus/ARG/34ESARGTOFOCCVV" },
  { id: 29, src: "corpus/ARG/38ESARGTOFOCCVV" },
  { id: 30, src: "corpus/ARG/39ESARGTOFOCCVV" },
  { id: 31, src: "corpus/ARG/40ESARGTOFOCCVV" },
  { id: 32, src: "corpus/ARG/42ESARGTOFOCCVV" },
  //legislation
  { id: 67, src: "legislation/ARG/01ESARGTOFOLEGIS" },
  { id: 68, src: "legislation/ARG/02ESARGTOFOLEGIS" },
  { id: 67, src: "legislation/ARG/03ESARGTOFOLEGIS" },
  { id: 67, src: "legislation/ARG/04ESARGTOFOLEGIS" },
  { id: 67, src: "legislation/ARG/05ESARGTOFOLEGIS" },

  //CA
  //corpus
  { id: 15, src: "corpus/CA/01CATOFOCCVV" },
  { id: 16, src: "corpus/CA/02CATOFOCCVV" },
  { id: 17, src: "corpus/CA/03CATOFOCCVV" },
  { id: 18, src: "corpus/CA/04CATOFOCCVV" },
  { id: 19, src: "corpus/CA/05CATOFOCCVV" },
  //legislation
  { id: 20, src: "legislation/CA/01CATOFOLEGIS" },
  { id: 21, src: "legislation/CA/02CATOFOLEGIS" },
  { id: 22, src: "legislation/CA/03CATOFOLEGIS" },

  //DE
  //corpus

  { id: 23, src: "corpus/DE/01DETOFOCCVV" },
  { id: 24, src: "corpus/DE/02DETOFOCCVV" },
  { id: 25, src: "corpus/DE/03DETOFOCCVV" },
  { id: 26, src: "corpus/DE/04DETOFOCCVV" },
  { id: 27, src: "corpus/DE/05DETOFOCCVV" },
  { id: 28, src: "corpus/DE/06DETOFOCCVV" },
  { id: 29, src: "corpus/DE/07DETOFOCCVV" },
  { id: 30, src: "corpus/DE/08DETOFOCCVV" },
  { id: 31, src: "corpus/DE/09DETOFOCCVV" },
  { id: 32, src: "corpus/DE/10DETOFOCCVV" },
  { id: 33, src: "corpus/DE/11DETOFOCCVV" },
  { id: 34, src: "corpus/DE/12DETOFOCCVV" },
  { id: 35, src: "corpus/DE/13DETOFOCCVV" },
  { id: 36, src: "corpus/DE/14DETOFOCCVV" },
  { id: 37, src: "corpus/DE/15DETOFOCCVV" },
  { id: 38, src: "corpus/DE/16DETOFOCCVV" },
  { id: 39, src: "corpus/DE/17DETOFOCCVV" },
  { id: 40, src: "corpus/DE/18DETOFOCCVV" },
  { id: 41, src: "corpus/DE/19DETOFOCCVV" },
  { id: 42, src: "corpus/DE/20DETOFOCCVV" },
  { id: 43, src: "corpus/DE/21DETOFOCCVV" },
  { id: 44, src: "corpus/DE/22DETOFOCCVV" },
  { id: 45, src: "corpus/DE/23DETOFOCCVV" },
  { id: 46, src: "corpus/DE/24DETOFOCCVV" },
  { id: 47, src: "corpus/DE/25DETOFOCCVV" },
  { id: 48, src: "corpus/DE/26DETOFOCCVV" },
  { id: 49, src: "corpus/DE/27DETOFOCCVV" },
  { id: 50, src: "corpus/DE/28DETOFOCCVV" },

  { id: 52, src: "corpus/DE/30DETOFOCCVV" },
  { id: 53, src: "corpus/DE/31DETOFOCCVV" },
  { id: 54, src: "corpus/DE/32DETOFOCCVV" },
  { id: 55, src: "corpus/DE/33DETOFOCCVV" },
  { id: 56, src: "corpus/DE/34DETOFOCCVV" },
  { id: 57, src: "corpus/DE/35DETOFOCCVV" },
  { id: 58, src: "corpus/DE/36DETOFOCCVV" },
  { id: 59, src: "corpus/DE/37DETOFOCCVV" },
  { id: 60, src: "corpus/DE/38DETOFOCCVV" },
  { id: 61, src: "corpus/DE/39DETOFOCCVV" },
  { id: 62, src: "corpus/DE/40DETOFOCCVV" },
  { id: 63, src: "corpus/DE/41DETOFOCCVV" },

  { id: 65, src: "corpus/DE/43DETOFOCCVV" },
  { id: 66, src: "corpus/DE/44DETOFOCCVV" },

  { id: 62, src: "corpus/DE/46DETOFOCCVV" },
  { id: 63, src: "corpus/DE/47DETOFOCCVV" },
  { id: 64, src: "corpus/DE/48DETOFOCCVV" },
  { id: 65, src: "corpus/DE/49DETOFOCCVV" },
  { id: 66, src: "corpus/DE/50DETOFOCCVV" },

  //legislation
  { id: 67, src: "legislation/DE/01DETOFOLEGIS" },
  { id: 68, src: "legislation/DE/02DETOFOLEGIS" },

  //EEUU
  //Corpus

  { id: 1, src: "corpus/EEUU/01ENUSTOFOCCVV" },
  { id: 2, src: "corpus/EEUU/02ENUSTOFOCCVV" },
  { id: 3, src: "corpus/EEUU/03ENUSTOFOCCVV" },
  { id: 4, src: "corpus/EEUU/04ENUSTOFOCCVV" },
  { id: 6, src: "corpus/EEUU/05ENUSTOFOCCVV" },
  { id: 7, src: "corpus/EEUU/06ENUSTOFOCCVV" },
  { id: 8, src: "corpus/EEUU/07ENUSTOFOCCVV" },
  { id: 9, src: "corpus/EEUU/08ENUSTOFOCCVV" },
  { id: 10, src: "corpus/EEUU/09ENUSTOFOCCVV" },
  { id: 11, src: "corpus/EEUU/10ENUSTOFOCCVV" },

  //Legislation

  { id: 12, src: "legislation/EEUU/01ENUSTOFOLEGIS" },
  { id: 13, src: "legislation/EEUU/03ENUSTOFOLEGIS" },
  { id: 14, src: "legislation/EEUU/04ENUSTOFOLEGIS" },

  //ESP
  //Corpus

  { id: 23, src: "corpus/ESP/01ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/03ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/04ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/05ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/06ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/07ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/08ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/10ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/11ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/12ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/13ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/14ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/15ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/16ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/17ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/18ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/19ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/20ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/21ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/22ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/23ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/24ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/25ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/26ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/27ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/28ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/29ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/31ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/32ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/34ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/35ESESPTOFOCCVV" },
  { id: 23, src: "corpus/ESP/45ESESPTOFOCCVV" },

  //legislation
  { id: 67, src: "legislation/ESP/01ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/02ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/03ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/04ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/05ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/06ESESPTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/07ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/08ESESPTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/09ESESPTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/10ESESPTOFOLEGIS" },
  { id: 67, src: "legislation/ESP/19ESESPTOFOLEGIS" },

  //Fr
  //corpus
  { id: 167, src: "corpus/FR/01FRFRATOFOCCVV" },
  { id: 168, src: "corpus/FR/02FRFRATOFOCCVV" },
  { id: 169, src: "corpus/FR/03FRFRATOFOCCVV" },
  { id: 170, src: "corpus/FR/04FRFRATOFOCCVV" },
  { id: 27, src: "corpus/FR/05FRFRATOFOCCVV" },
  { id: 28, src: "corpus/FR/06FRFRATOFOCCVV" },
  { id: 29, src: "corpus/FR/07FRFRATOFOCCVV" },
  { id: 30, src: "corpus/FR/08FRFRATOFOCCVV" },
  { id: 31, src: "corpus/FR/09FRFRATOFOCCVV" },
  { id: 32, src: "corpus/FR/10FRFRATOFOCCVV" },
  { id: 23, src: "corpus/FR/11FRFRATOFOCCVV" },
  { id: 24, src: "corpus/FR/12FRFRATOFOCCVV" },
  { id: 25, src: "corpus/FR/13FRFRATOFOCCVV" },
  { id: 26, src: "corpus/FR/14FRFRATOFOCCVV" },
  { id: 27, src: "corpus/FR/15FRFRATOFOCCVV" },
  { id: 28, src: "corpus/FR/16FRFRATOFOCCVV" },
  { id: 29, src: "corpus/FR/17FRFRATOFOCCVV" },
  { id: 30, src: "corpus/FR/18FRFRATOFOCCVV" },
  { id: 31, src: "corpus/FR/19FRFRATOFOCCVV" },
  { id: 32, src: "corpus/FR/20FRFRATOFOCCVV" },
  { id: 23, src: "corpus/FR/21FRFRATOFOCCVV" },
  { id: 24, src: "corpus/FR/22FRFRATOFOCCVV" },
  { id: 25, src: "corpus/FR/23FRFRATOFOCCVV" },
  { id: 26, src: "corpus/FR/24FRFRATOFOCCVV" },
  { id: 27, src: "corpus/FR/25FRFRATOFOCCVV" },
  { id: 28, src: "corpus/FR/26FRFRATOFOCCVV" },
  { id: 29, src: "corpus/FR/27FRFRATOFOCCVV" },
  { id: 30, src: "corpus/FR/28FRFRATOFOCCVV" },
  { id: 31, src: "corpus/FR/29FRFRATOFOCCVV" },
  { id: 32, src: "corpus/FR/30FRFRATOFOCCVV" },
  { id: 23, src: "corpus/FR/31FRFRATOFOCCVV" },
  { id: 24, src: "corpus/FR/32FRFRATOFOCCVV" },
  { id: 25, src: "corpus/FR/33FRFRATOFOCCVV" },
  { id: 26, src: "corpus/FR/34FRFRATOFOCCVV" },
  { id: 27, src: "corpus/FR/35FRFRATOFOCCVV" },
  { id: 28, src: "corpus/FR/36FRFRATOFOCCVV" },
  { id: 29, src: "corpus/FR/37FRFRATOFOCCVV" },
  { id: 30, src: "corpus/FR/38FRFRATOFOCCVV" },
  { id: 31, src: "corpus/FR/39FRFRATOFOCCVV" },
  { id: 32, src: "corpus/FR/40FRFRATOFOCCVV" },
  { id: 26, src: "corpus/FR/41FRFRATOFOCCVV" },
  { id: 27, src: "corpus/FR/42FRFRATOFOCCVV" },
  { id: 28, src: "corpus/FR/43FRFRATOFOCCVV" },
  { id: 29, src: "corpus/FR/44FRFRATOFOCCVV" },
  { id: 30, src: "corpus/FR/45FRFRATOFOCCVV" },
  { id: 31, src: "corpus/FR/46FRFRATOFOCCVV" },
  { id: 32, src: "corpus/FR/47FRFRATOFOCCVV" },

  //legislation
  { id: 67, src: "legislation/FR/01FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/02FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/03FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/04FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/05FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/06FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/07FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/08FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/09FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/10FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/11FRFRATOFOLEGIS" },
  { id: 67, src: "legislation/FR/12FRFRATOFOLEGIS" },

  //IR
  //Corpus

  { id: 23, src: "corpus/IR/01ENIRLTOFOCCVV" },
  { id: 24, src: "corpus/IR/02ENIRLTOFOCCVV" },
  { id: 25, src: "corpus/IR/03ENIRLTOFOCCVV" },
  { id: 26, src: "corpus/IR/04ENIRLTOFOCCVV" },
  { id: 27, src: "corpus/IR/05ENIRLTOFOCCVV" },
  { id: 28, src: "corpus/IR/06ENIRLTOFOCCVV" },
  { id: 29, src: "corpus/IR/07ENIRLTOFOCCVV" },
  { id: 30, src: "corpus/IR/08ENIRLTOFOCCVV" },
  { id: 31, src: "corpus/IR/09ENIRLTOFOCCVV" },
  { id: 32, src: "corpus/IR/10ENIRLTOFOCCVV" },

  //legislation
  { id: 67, src: "legislation/IR/01ENIRLTOFOLEGIS" },
  { id: 68, src: "legislation/IR/02ENIRLTOFOLEGIS" },
  { id: 67, src: "legislation/IR/03ENIRLTOFOLEGIS" },

  //IT
  //corpus

  { id: 23, src: "corpus/IT/01ITTOFOCCVV" },
  { id: 24, src: "corpus/IT/02ITTOFOCCVV" },
  { id: 25, src: "corpus/IT/03ITTOFOCCVV" },
  { id: 26, src: "corpus/IT/04ITTOFOCCVV" },
  { id: 27, src: "corpus/IT/05ITTOFOCCVV" },
  { id: 28, src: "corpus/IT/06ITTOFOCCVV" },
  { id: 29, src: "corpus/IT/07ITTOFOCCVV" },
  { id: 30, src: "corpus/IT/08ITTOFOCCVV" },
  { id: 31, src: "corpus/IT/09ITTOFOCCVV" },
  { id: 32, src: "corpus/IT/10ITTOFOCCVV" },
  { id: 23, src: "corpus/IT/11ITTOFOCCVV" },
  { id: 24, src: "corpus/IT/12ITTOFOCCVV" },
  { id: 25, src: "corpus/IT/13ITTOFOCCVV" },
  { id: 26, src: "corpus/IT/14ITTOFOCCVV" },
  { id: 27, src: "corpus/IT/15ITTOFOCCVV" },
  { id: 29, src: "corpus/IT/16ITTOFOCCVV" },
  { id: 30, src: "corpus/IT/17ITTOFOCCVV" },
  { id: 31, src: "corpus/IT/18ITTOFOCCVV" },
  { id: 32, src: "corpus/IT/19ITTOFOCCVV" },
  { id: 23, src: "corpus/IT/20ITTOFOCCVV" },
  { id: 24, src: "corpus/IT/21ITTOFOCCVV" },
  { id: 25, src: "corpus/IT/22ITTOFOCCVV" },
  { id: 26, src: "corpus/IT/23ITTOFOCCVV" },
  { id: 27, src: "corpus/IT/24ITTOFOCCVV" },
  { id: 28, src: "corpus/IT/25ITTOFOCCVV" },
  { id: 29, src: "corpus/IT/26ITTOFOCCVV" },
  { id: 30, src: "corpus/IT/27ITTOFOCCVV" },
  { id: 31, src: "corpus/IT/28ITTOFOCCVV" },
  { id: 32, src: "corpus/IT/29ITTOFOCCVV" },
  { id: 23, src: "corpus/IT/30ITTOFOCCVV" },
  { id: 24, src: "corpus/IT/31ITTOFOCCVV" },
  { id: 25, src: "corpus/IT/32ITTOFOCCVV" },
  { id: 26, src: "corpus/IT/33ITTOFOCCVV" },
  { id: 27, src: "corpus/IT/34ITTOFOCCVV" },
  { id: 28, src: "corpus/IT/35ITTOFOCCVV" },
  { id: 29, src: "corpus/IT/36ITTOFOCCVV" },
  { id: 30, src: "corpus/IT/37ITTOFOCCVV" },
  { id: 31, src: "corpus/IT/38ITTOFOCCVV" },
  { id: 32, src: "corpus/IT/39ITTOFOCCVV" },
  { id: 23, src: "corpus/IT/40ITTOFOCCVV" },
  { id: 24, src: "corpus/IT/41ITTOFOCCVV" },
  { id: 25, src: "corpus/IT/42ITTOFOCCVV" },
  { id: 26, src: "corpus/IT/43ITTOFOCCVV" },
  { id: 27, src: "corpus/IT/46ITTOFOCCVV" },
  { id: 28, src: "corpus/IT/49ITTOFOCCVV" },
  //Legislation
  { id: 67, src: "legislation/IT/01ITTOFOCCVVLEG" },
  { id: 67, src: "legislation/IT/02ITTOFOCCVVLEG" },
  { id: 67, src: "legislation/IT/03ITTOTXTCCVVLEG" },

  //  UE
  // Legislation
  { id: 67, src: "legislation/UE/01ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/02ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/03ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/04ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/05ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/06ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/07ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/08ESEUTOFOLEGIS" },
  { id: 67, src: "legislation/UE/09ESEUTOFOLEGIS" },

  //UK
  //Corpus
  { id: 23, src: "corpus/UK/01ENUKTOTXTCCVV" },
  { id: 24, src: "corpus/UK/02ENUKTOFOCCVV" },
  { id: 25, src: "corpus/UK/03ENUKTOFOCCVV" },
  //legislation
  { id: 67, src: "legislation/UK/01ENUKTOTXTCCVV" },
  { id: 68, src: "legislation/UK/02ENUKTOTXTCCVV" },
  { id: 67, src: "legislation/UK/03ENUKTOTXTCCVV" },
  { id: 67, src: "legislation/UK/04ENUKTOTXTCCVV" },
];
