export const dataTable= [
    {
     "ES (ESP)": "Abogado",
     "ES (ARG)": "Abogado",
     "EN (UK)": "Advocate\/Solicitor\/Lawyer",
     "EN (US)": "Advocate\/Lawyer",
     "EN (IR)": "Solicitor",
     "FR": "Avocat",
     "IT": "avvocato(-a)",
     "DE": "Anwalt",
     "CA": "advocat"
    },
    {
     "ES (ESP)": "Acreedor",
     "ES (ARG)": "Acreedor",
     "EN (UK)": "Creditor",
     "EN (US)": "Creditor",
     "EN (IR)": "Creditor",
     "FR": "Créancier\/Cocréancier",
     "IT": "creditore(-trice)",
     "DE": "Gläubiger",
     "CA": "acreedor"
    },
    {
     "ES (ESP)": "Acto",
     "ES (ARG)": "Acto",
     "EN (UK)": "Event\/Occurrence",
     "EN (US)": "Event\/Occurrence",
     "EN (IR)": "Event",
     "FR": "Acte\/évenement",
     "IT": "atto",
     "DE": "Handlung",
     "CA": "acte"
    },
    {
     "ES (ESP)": "Acta notarial",
     "ES (ARG)": "Acta notarial",
     "EN (UK)": "Notarial certificate",
     "EN (US)": "Notarial certificate",
     "EN (IR)": "Notarial act\/Notarial deed",
     "FR": "Acte notarié",
     "IT": "atto notarile",
     "DE": "notarielle Urkunde, notarielle Beurkundung",
     "CA": "acta notarial"
    },
    {
     "ES (ESP)": "Acuerdo legal informal",
     "ES (ARG)": "Acuerdo legal informal",
     "EN (UK)": "Memorandum",
     "EN (US)": "Memorandum",
     "EN (IR)": "Memorandum",
     "FR": "Accord informel\/Accord tacite",
     "IT": "accordo delle parti",
     "DE": "informelle Vereinbarung",
     "CA": "acord legal informal"
    },
    {
     "ES (ESP)": "Acuerdo\/pacto",
     "ES (ARG)": "Acuerdo\/pacto",
     "EN (UK)": "Agreement\/Contract",
     "EN (US)": "Agreement\/Contract",
     "EN (IR)": "Agreement\/contract",
     "FR": "Accord\/Contrat\/Engagement contractuel",
     "IT": "accordo\/patto",
     "DE": "Vertrag\/Abkommen",
     "CA": "acord\/pacte"
    },
    {
     "ES (ESP)": "Administrador",
     "ES (ARG)": "Administrador",
     "EN (UK)": "Administrator",
     "EN (US)": "Administrator",
     "EN (IR)": "Administrator",
     "FR": "Administrateur",
     "IT": "amministratore(-trice)",
     "DE": "Verwalter",
     "CA": "administrador"
    },
    {
     "ES (ESP)": "Adquiriente\/comprador\/parte compradora",
     "ES (ARG)": "Adquiriente\/comprador\/parte compradora",
     "EN (UK)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "EN (US)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "EN (IR)": "Acquirer\/Acquiring party\/buyer\/purcharser",
     "FR": "Acquéreur\/Acheteur\/Acquéreur",
     "IT": "acquirente\/compratore\/parte compratrice",
     "DE": "Erwerber\/Käufer",
     "CA": "comprador\/part compradora "
    },
    {
     "ES (ESP)": "Adquirir\/comprar",
     "ES (ARG)": "Adquirir\/comprar",
     "EN (UK)": "To acquirer [not very frequently]\/To buy\/To purchase",
     "EN (US)": "To acquirer [not very frequently]\/To buy\/To purchase",
     "EN (IR)": "To acquirer [not very frequently]\/To buy\/To purchase",
     "FR": "Acquérir\/Acheter",
     "IT": "acquistare\/comprare",
     "DE": "erwerben\/kaufen",
     "CA": "adquirir\/comprar"
    },
    {
     "ES (ESP)": "Agente inmobiliario",
     "ES (ARG)": "Agente inmobiliario",
     "EN (UK)": "Real(-)estate broker\/Broker",
     "EN (US)": "Real(-)estate broker\/Broker\/Realtor",
     "EN (IR)": "Real(-)estate broker\/Broker",
     "FR": "Agent immobilier",
     "IT": "agente immobiliare",
     "DE": "Grundstücksmakler",
     "CA": "agent immobiliari"
    },
    {
     "ES (ESP)": "Anexo",
     "ES (ARG)": "Anexo",
     "EN (UK)": "Annex\/Annexe\/Addendum",
     "EN (US)": "Annex\/Addendum",
     "EN (IR)": "Annexed",
     "FR": "Annexe",
     "IT": "allegato",
     "DE": "Anhang",
     "CA": "annex"
    },
    {
     "ES (ESP)": "Arbitraje\/arbitrio",
     "ES (ARG)": "Arbitraje\/arbitrio",
     "EN (UK)": "Arbitration",
     "EN (US)": "Arbitration",
     "EN (IR)": "Arbitration",
     "FR": "Arbitrage",
     "IT": "arbitraggio",
     "DE": "Schieds(gericht)verfahren \/ Schlichtung \/ Arbitrage",
     "CA": "arbitratge\/arbitri"
    },
    {
     "ES (ESP)": "Arras\/Señal",
     "ES (ARG)": "Arras\/Señal",
     "EN (UK)": "Down-payment",
     "EN (US)": "Down payment",
     "EN (IR)": "Down-payment",
     "FR": "Arrhes\/Caution",
     "IT": "caparra",
     "DE": "Draufgabe \/ Vorauszahlung",
     "CA": "arres\/paga i senyal"
    },
    {
     "ES (ESP)": "Arrendador",
     "ES (ARG)": "Arrendador\/Locador",
     "EN (UK)": "Lessor\/Renter\/Hirer",
     "EN (US)": "Lessor\/Renter",
     "EN (IR)": "Lessor\/Renter\/Hirer",
     "FR": "Bailleur\/Locateur\/Propriétaire\/Loueur",
     "IT": "locatore(-trice)",
     "DE": "Verpächter",
     "CA": "arrendador"
    },
    {
     "ES (ESP)": "Arrendamiento\/Alquiler",
     "ES (ARG)": "Arrendamiento\/Alquiler\/Locación",
     "EN (UK)": "Lease\/Leasing\/Leasehold\/Rental\/Rent\/Hire",
     "EN (US)": "Lease\/Leasing\/Rental\/Rent",
     "EN (IR)": "Lease rental hire\/Leasehold",
     "FR": "Contrat de location\/Location\/Loyer",
     "IT": "affitto\/locazione",
     "DE": "Verpachtung \/ Vermietung",
     "CA": "arrendament\/lloguer"
    },
    {
     "ES (ESP)": "Arrendamiento con opción a compra\/Alquiler con opción a compra",
     "ES (ARG)": "Arrendamiento con opción a compra\/Alquiler con opción a compra",
     "EN (UK)": "Rental purchase\/Rent-to-buy\/Rent-to-own",
     "EN (US)": "Rental purchase\/Rent-to-buy\/Rent-to-own",
     "EN (IR)": "Rental purchase\/Rent-to-buy\/Rent-to-own",
     "FR": "Location avec option d'achat (LOA), Crédit-bail",
     "IT": "affitto con opzione di acquisto\/locazione con opzione di acquisto",
     "DE": "Verpachtung mit Kaufoption \/ Mietkauf \/ Miete mit Kaufoption",
     "CA": "arrendament amb opció de compra\/Lloguer amb opció de compra "
    },
    {
     "ES (ESP)": "Arrendatario\/Inquilino",
     "ES (ARG)": "Arrendatario\/Inquilino\/Locatario",
     "EN (UK)": "Lessee\/Tenant\/Leaseholder",
     "EN (US)": "Lessee\/Tenant\/Leaseholder",
     "EN (IR)": "Lessee\/\nLeasehold",
     "FR": "Locataire",
     "IT": "locatario(-a)\/inquilino(-a)",
     "DE": "Pächter",
     "CA": "arrendatari\/llogater"
    },
    {
     "ES (ESP)": "Artículo",
     "ES (ARG)": "Artículo",
     "EN (UK)": "Section\/Article",
     "EN (US)": "Section\/Article",
     "EN (IR)": "Section\/Article",
     "FR": "Article",
     "IT": "articolo",
     "DE": "Artikel",
     "CA": "article"
    },
    {
     "ES (ESP)": "Autorización",
     "ES (ARG)": "Autorización",
     "EN (UK)": "Authorization",
     "EN (US)": "Authorisation",
     "EN (IR)": "Authorization",
     "FR": "Autorisation",
     "IT": "autorizzazione",
     "DE": "Zulassung",
     "CA": "autorització"
    },
    {
     "ES (ESP)": "Bancario",
     "ES (ARG)": "Bancario",
     "EN (UK)": "Banking",
     "EN (US)": "Banking",
     "EN (IR)": "Banking",
     "FR": "Bancaire",
     "IT": "bancario",
     "DE": "Bank- \/ bankmäßig",
     "CA": "bancari"
    },
    {
     "ES (ESP)": "Bien",
     "ES (ARG)": "Bien",
     "EN (UK)": "Asset\/Good",
     "EN (US)": "Asset\/Good",
     "EN (IR)": "Asset\/Good",
     "FR": "Bien",
     "IT": "bene",
     "DE": "Sache \/ Gut \/ Habe \/ Vermögensgegenstand",
     "CA": "bé"
    },
    {
     "ES (ESP)": "Bien accesorio",
     "ES (ARG)": "Cosa accesoria",
     "EN (UK)": "Fittings\/Fixtures",
     "EN (US)": "Fittings\/Fixtures",
     "EN (IR)": "Fittings\/Fixtures",
     "FR": "Bien rattaché",
     "IT": "bene accessorio",
     "DE": "Zubehör",
     "CA": "bé accessori"
    },
    {
     "ES (ESP)": "Bienes gananciales",
     "ES (ARG)": "Bienes gananciales",
     "EN (UK)": "Matrimonial Property",
     "EN (US)": "Matrimonial Property",
     "EN (IR)": "Matrimonial assets\/\nMatrimonial properties",
     "FR": "Bien matrimoniaux",
     "IT": "beni comuni",
     "DE": "Gesamtgut \/Errungenschaftsgemeinschaft",
     "CA": "béns ganancials"
    },
    {
     "ES (ESP)": "Bien mueble",
     "ES (ARG)": "Bien mueble",
     "EN (UK)": "Chattel",
     "EN (US)": "Chattel",
     "EN (IR)": "Chattel",
     "FR": "Bien mobilier",
     "IT": "bene mobile",
     "DE": "bewegliches Vermögen \/ bewegliche Güter \/ bewegliche Sachen",
     "CA": "bé moble"
    },
    {
     "ES (ESP)": "Buena fe",
     "ES (ARG)": "Buena fe",
     "EN (UK)": "Good faith",
     "EN (US)": "Goodwill",
     "EN (IR)": "Goodwill",
     "FR": "Bonne foi",
     "IT": "buona fede",
     "DE": "gutgläubig",
     "CA": "bona fe"
    },
    {
     "ES (ESP)": "Cancelación",
     "ES (ARG)": "Cancelación",
     "EN (UK)": "Cancellation",
     "EN (US)": "Cancellation",
     "EN (IR)": "Cancellation",
     "FR": "Annulation",
     "IT": "cancellazione",
     "DE": "Ausgleich",
     "CA": "cancel·lació"
    },
    {
     "ES (ESP)": "Cantidad\/Importe\/Monto\/Cuantía\/Suma",
     "ES (ARG)": "Cantidad\/Importe\/Monto\/Cuantía\/Suma",
     "EN (UK)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (US)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (IR)": "Amount",
     "FR": "Quantité\/Montant\/Somme",
     "IT": "quantità\/importo\/somma",
     "DE": "Betrag \/ Geldbetrag \/ Gesamtbetrag \/ Geldsumme \/ Summe "
    },
    {
     "ES (ESP)": "Capacidad\/Facultad",
     "ES (ARG)": "Capacidad\/Facultad",
     "EN (UK)": "Capacity",
     "EN (US)": "Capacity",
     "EN (IR)": "Capacity",
     "FR": "Capacité\/Pouvoir",
     "IT": "capacità\/facoltà",
     "DE": "Rechtsfähigkeit \/ Befügnis",
     "CA": "capacitat\/facultat"
    },
    {
     "ES (ESP)": "Capacidad de obrar",
     "ES (ARG)": "Capacidad de obrar",
     "EN (UK)": "Legal capacity",
     "EN (US)": "Legal capacity",
     "EN (IR)": "Legal capacity",
     "FR": "Capacité juridique\/capacité légale\/capacité de jouissance",
     "IT": "capacità per operare",
     "DE": "Handlungsfähigkeit",
     "CA": "capacitat d'obrar"
    },
    {
     "ES (ESP)": "Carga",
     "ES (ARG)": "Carga",
     "EN (UK)": "Charge",
     "EN (US)": "Charge",
     "EN (IR)": "Burden\/\nCharge",
     "FR": "Charge",
     "IT": "addebbito",
     "DE": "Last",
     "CA": "càrrega"
    },
    {
     "ES (ESP)": "Caso",
     "ES (ARG)": "Caso",
     "EN (UK)": "Case",
     "EN (US)": "Case",
     "EN (IR)": "Case",
     "FR": "Cas",
     "IT": "caso",
     "DE": "Fall",
     "CA": "cas\/assumpte"
    },
    {
     "ES (ESP)": "Catastro\/Registro de la propiedad",
     "ES (ARG)": "Registro de la Propiedad\/Registro de la Propiedad Inmueble",
     "EN (UK)": "Land registry\/Local deeds registry",
     "EN (US)": "Real Property Official Record",
     "EN (IR)": "Land Registry",
     "FR": "Cadastre\/Enregistrement de la propriété",
     "IT": "catasto\/registro immobiliare",
     "DE": "Kataster \/ Grundstückregister",
     "CA": "cadastre\/registre de la propietat "
    },
    {
     "ES (ESP)": "Certificado",
     "ES (ARG)": "Certificado",
     "EN (UK)": "Certificate",
     "EN (US)": "Certificate",
     "EN (IR)": "Certificate",
     "FR": "Certificat",
     "IT": "certificato",
     "DE": "Bescheinigung",
     "CA": "certificat"
    },
    {
     "ES (ESP)": "Cláusula\/Estipulación\/Disposición",
     "ES (ARG)": "Cláusula\/Estipulación\/Disposición",
     "EN (UK)": "Clause\/provition\/disposition",
     "EN (US)": "Clause\/provition\/disposition",
     "EN (IR)": "Provision",
     "FR": "Clause\/Stipulation\/Disposition",
     "IT": "clausola\/stipulazione\/disposizione",
     "DE": "Klausel \/ Abmachung \/Vereinbarung \/ Bestimmung",
     "CA": "clàusula\/estipulació\/disposició "
    },
    {
     "ES (ESP)": "Comiso\/Decomiso\/Confiscación",
     "ES (ARG)": "Comiso\/Decomiso\/Confiscación",
     "EN (UK)": "Forfeiture",
     "EN (US)": "Forfeiture",
     "EN (IR)": "Forfeiture",
     "FR": "Confiscation",
     "IT": "sequestro\/confisca",
     "DE": "Beschlagnahme \/Einziehung \/ Verfall \/ Beschlagnahmung",
     "CA": "comís\/confiscació"
    },
    {
     "ES (ESP)": "Comparecen\/Intervienen\/Reunidos",
     "ES (ARG)": "Entre\/Se reúnen",
     "EN (UK)": "Between",
     "EN (US)": "Between",
     "EN (IR)": "Between",
     "FR": "Entre\/Entre les sousignés",
     "IT": "Compariscono\/intervengono\/riuniti",
     "DE": "Erschienen sind \/ erschien \/ ist\/sind anwesend",
     "CA": "compareixen\/intervenen\/reunits "
    },
    {
     "ES (ESP)": "Comprador\/Parte compradora\/Adquiriente",
     "ES (ARG)": "Comprador\/Parte compradora\/Adquiriente",
     "EN (UK)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "EN (US)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "EN (IR)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "FR": "Acquéreur\/Acheteur\/Acquéreur",
     "IT": "compratore\/parte compratrice\/acquirente",
     "DE": "Käufer \/ Erwerber \/ Abnehmer",
     "CA": "comprador\/part compradora\/adquirent "
    },
    {
     "ES (ESP)": "Comprar\/Adquirir",
     "ES (ARG)": "Comprar\/Adquirir",
     "EN (UK)": "To acquirer [not very frequently]\/To buy\/To purchase",
     "EN (US)": "To acquirer [not very frequently]\/To buy\/To purchase",
     "EN (IR)": "To acquirer [not very frequently]\/To buy\/To purchase",
     "FR": "Acheter\/Acquérir",
     "IT": "comprare\/acquistare",
     "DE": "kaufen \/ erwerben",
     "CA": "comprar\/adquirir"
    },
    {
     "ES (ESP)": "Compraventa",
     "ES (ARG)": "Compraventa",
     "EN (UK)": "Purchase and sale",
     "EN (US)": "Purchase and sale",
     "EN (IR)": "Purchase and sale",
     "FR": "Vente",
     "IT": "compravendita",
     "DE": "Kauf",
     "CA": "compravenda"
    },
    {
     "ES (ESP)": "Comunicación\/Notificación",
     "ES (ARG)": "Comunicación\/Notificación",
     "EN (UK)": "Notice\/Communication",
     "EN (US)": "Notice\/Communication",
     "EN (IR)": "Notice\/\nCommunication",
     "FR": "Communication\/Avis\/Préavis\/Notification",
     "IT": "comunicazione\/notifica",
     "DE": "Mitteilung \/ Benachrigtigung \/ Zustellung",
     "CA": "comunicació\/notificació"
    },
    {
     "ES (ESP)": "Comunidad",
     "ES (ARG)": "Comunidad",
     "EN (UK)": "Community",
     "EN (US)": "Community",
     "EN (IR)": "Community",
     "FR": "Communauté",
     "IT": "condominio",
     "DE": "Gemeinschaft",
     "CA": "comunitat"
    },
    {
     "ES (ESP)": "Con arreglo a\/Conforme a\/ Lo dispuesto en\/Regulado por\/En virtud de",
     "ES (ARG)": "Con arreglo a\/Conforme a\/ Lo dispuesto en\/Regulado por\/En virtud de\/Sujección al",
     "EN (UK)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (US)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (IR)": "Pursuant to\/\nIn accordance with\/ \nIn relation to\/",
     "FR": "Conformément à\/Les dispositions\/Réglementée par\/En vertu de",
     "IT": "in base a\/secondo quanto previsto\/secondo quanto stabilito\/in conformità a",
     "DE": "nach Maßgabe von \/ gemäß \/ auf Grund \/ entsprechend den Bestimmungen",
     "CA": "Conforme al\/D'acord amb\/Segons s'estableix\/ segons el que disposa el\/en virtut de "
    },
    {
     "ES (ESP)": "Condición\/Requisito",
     "ES (ARG)": "Condición\/Requisito",
     "EN (UK)": "Condition\/Requirement",
     "EN (US)": "Condition\/Requirement",
     "EN (IR)": "Condition",
     "FR": "Condition\/Exigence",
     "IT": "condizione\/requisito",
     "DE": "Voraussetzung \/ Vorbedingung \/ Erfordernis",
     "CA": "condició\/requisit"
    },
    {
     "ES (ESP)": "Condominio\/Copropiedad\/Propiedad comunitaria",
     "ES (ARG)": "Condominio\/Copropiedad\/Propiedad comunitaria",
     "EN (UK)": "Condominium",
     "EN (US)": "Condominium",
     "EN (IR)": "Condominium",
     "FR": "Copropriété",
     "IT": "comproprietà\/proprietà condominiale",
     "DE": "Miteigentum \/ Gemeinschaftsbesitz \/Gemeischaftseigentum",
     "CA": "condomini\/copropietat\/propietat comunitària "
    },
    {
     "ES (ESP)": "Confiscación\/Comiso\/Decomiso",
     "ES (ARG)": "Confiscación\/Comiso\/Decomiso",
     "EN (UK)": "Forfeiture",
     "EN (US)": "Forfeiture",
     "EN (IR)": "Forfeiture",
     "FR": "Confiscation",
     "IT": "confisca\/sequestro",
     "DE": "Beschlagnahme \/Einziehung \/ Verfall",
     "CA": "confiscació\/comís"
    },
    {
     "ES (ESP)": "Conforme a\/Con arreglo a\/Lo dispuesto en\/Regulado por\/En virtud de",
     "ES (ARG)": "Con arreglo a\/Conforme a\/ Lo dispuesto en\/Regulado por\/En virtud de\/Sujección al",
     "EN (UK)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (US)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (IR)": "Pursuant to\/\nIn accordance with\/ \nIn relation to\/",
     "FR": "Conformément à\/Les dispositions\/Réglementée par\/En vertu de",
     "IT": "in base a\/secondo quanto previsto\/secondo quanto stabilito\/in conformità a",
     "DE": "nach Maßgabe von \/ gemäß \/ auf Grund \/ entsprechend den Bestimmungen",
     "CA": "Conforme al\/D'acord amb\/Segons s'estableix\/ segons el que disposa el\/en virtut de "
    },
    {
     "ES (ESP)": "Consentimiento",
     "ES (ARG)": "Consentimiento\/Asentimiento",
     "EN (UK)": "Consent\/Assent",
     "EN (US)": "Consent\/Assent",
     "EN (IR)": "Consent",
     "FR": "Consentement",
     "IT": "consenso",
     "DE": "Zustimmung",
     "CA": "consentiment"
    },
    {
     "ES (ESP)": "Contestación\/Repuesta",
     "ES (ARG)": "Respuesta",
     "EN (UK)": "Reply",
     "EN (US)": "Reply",
     "EN (IR)": "Rejoinder\/\nReply",
     "FR": "Réponse",
     "IT": "risposta",
     "DE": "Antwort",
     "CA": "contestació\/resposta"
    },
    {
     "ES (ESP)": "Contrato",
     "ES (ARG)": "Contrato\/Boleto",
     "EN (UK)": "Contract\/Agreement",
     "EN (US)": "Contract\/Agreement",
     "EN (IR)": "Contract\/\nAgreement",
     "FR": "Contrat",
     "IT": "contratto",
     "DE": "Vertrag",
     "CA": "contracte"
    },
    {
     "ES (ESP)": "Contrato de arrendamiento\/Contrato de alquiler",
     "ES (ARG)": "Contrato de arrendamiento\/Contrato de alquiler\/Contrato de locación",
     "EN (UK)": "Hire agreement\/Lease",
     "EN (US)": "Hire agreement\/Lease",
     "EN (IR)": "Lease rental hire\/Leasehold",
     "FR": "Controverse",
     "IT": "contratto di locazione\/contratto di affitto",
     "DE": "Pachtvertrag \/ Mietvertrag",
     "CA": "contracte d'arrendament\/contracte de lloguer "
    },
    {
     "ES (ESP)": "Contrato de compraventa",
     "ES (ARG)": "Contrato de compraventa\/Boleto de compraventa",
     "EN (UK)": "Purchase and sale agreement\/Purchase and sale contract\/Contract (of\/for) sale",
     "EN (US)": "Purchase and sale agreement\/Purchase and sale contract\/Contracto (of\/for) sale\/Agreeement to buy or sell\/Selling form",
     "EN (IR)": "Purchase and sale agreement\/Purchase and sale contract\/Contract (of\/for) sale",
     "FR": "Contrat de location\/Location\/Loyer",
     "IT": "contratto di compravendita",
     "DE": "Kaufvertrag \/ Verkaufsvertrag",
     "CA": "contracte de compravenda"
    },
    {
     "ES (ESP)": "Controversia\/Litigio",
     "ES (ARG)": "Controversia\/Litigio",
     "EN (UK)": "Dispute",
     "EN (US)": "Dispute",
     "EN (IR)": "Dispute",
     "FR": "Controverse\/Litige",
     "IT": "controversia\/causa",
     "DE": "Streit \/ Streitfall \/Streitigkeit",
     "CA": "controvèrsia\/litigi"
    },
    {
     "ES (ESP)": "Cónyuge",
     "ES (ARG)": "Cónyuge\/Esposo",
     "EN (UK)": "Spouse",
     "EN (US)": "Spouse",
     "EN (IR)": "Spouse",
     "FR": "Conjoint€\/Époux\/Épouse",
     "IT": "coniuge",
     "DE": "Ehegatte",
     "CA": "cònjuge"
    },
    {
     "ES (ESP)": "Copropiedad\/Condominio\/Propiedad comunitaria",
     "ES (ARG)": "Copropiedad\/Condominio\/Propiedad comunitaria",
     "EN (UK)": "Condominium",
     "EN (US)": "Condominium",
     "EN (IR)": "Condominium",
     "FR": "Copropriété",
     "IT": "comproprietà\/proprietà condominiale",
     "DE": "Miteigentum \/ Gemeinschaftsbesitz \/Gemeischaftseigentum",
     "CA": "condomini\/copropietat\/propietat comunitària "
    },
    {
     "ES (ESP)": "Cuantía\/Cantidad\/Importe\/Suma\/Monto",
     "ES (ARG)": "Cuantía\/Cantidad\/Importe\/Suma\/Monto",
     "EN (UK)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (US)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (IR)": "Amount",
     "FR": "Quantité\/Montant\/Somme",
     "IT": "quantità\/importo\/somma",
     "DE": "Betrag \/ Geldbetrag \/ Gesamtbetrag \/ Geldsumme \/ Summe",
     "CA": "quantia\/quantitat\/import\/suma\/ "
    },
    {
     "ES (ESP)": "Cuenta",
     "ES (ARG)": "Cuenta",
     "EN (UK)": "Account",
     "EN (US)": "Account",
     "EN (IR)": "Account",
     "FR": "Compte",
     "IT": "conto",
     "DE": "Konto",
     "CA": "compte"
    },
    {
     "ES (ESP)": "Declaración jurada",
     "ES (ARG)": "Declaración jurada",
     "EN (UK)": "Affidavit",
     "EN (US)": "Affidavit",
     "EN (IR)": "Affidavit",
     "FR": "Affidavit déclaration sous serment",
     "IT": "dichiarazione giurata",
     "DE": "eidesstattliche Erklärung",
     "CA": "declaració jurada"
    },
    {
     "ES (ESP)": "Decomiso\/Comiso\/Confiscación",
     "ES (ARG)": "Decomiso\/Comiso\/Confiscación",
     "EN (UK)": "Forfeiture",
     "EN (US)": "Forfeiture",
     "EN (IR)": "Forfeiture",
     "FR": "Confiscation",
     "IT": "sequestro\/confisca",
     "DE": "Beschlagnahme \/Einziehung \/ Verfall",
     "CA": "comís\/confiscació"
    },
    {
     "ES (ESP)": "De conformidad con\/Conforme a\/Con arreglo a\/Lo dispuesto en\/Regulado por\/En virtud de",
     "ES (ARG)": "De conformidad con\/Conforme a\/Con arreglo a\/Lo dispuesto en\/Regulado por\/En virtud de\/Sujección al",
     "EN (UK)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (US)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (IR)": "Pursuant to\/\nIn accordance with\/ \nIn relation to\/",
     "FR": "Conformément à\/Les dispositions\/Réglementée par\/En vertu de",
     "IT": "in base a\/secondo quanto previsto\/secondo quanto stabilito\/in conformità a",
     "DE": "nach Maßgabe von \/ gemäß \/ auf Grund \/ entsprechend den Bestimmungen",
     "CA": "Conforme al\/D'acord amb\/Segons s'estableix\/ segons el que disposa el\/en virtut de "
    },
    {
     "ES (ESP)": "Demora",
     "ES (ARG)": "Demora",
     "EN (UK)": "Delay",
     "EN (US)": "Delay",
     "EN (IR)": "Delay",
     "FR": "Délai d'exécution",
     "IT": "ritardo",
     "DE": "Verzug",
     "CA": "demora"
    },
    {
     "ES (ESP)": "Definición",
     "ES (ARG)": "Definición",
     "EN (UK)": "Definition",
     "EN (US)": "Definition",
     "EN (IR)": "Definition",
     "FR": "Définition",
     "IT": "definizione",
     "DE": "Definition",
     "CA": "definició"
    },
    {
     "ES (ESP)": "Depósito",
     "ES (ARG)": "Depósito",
     "EN (UK)": "Deposit",
     "EN (US)": "Deposit",
     "EN (IR)": "Deposit",
     "FR": "Dépôt",
     "IT": "deposito (cauzionale)\/cauzione",
     "DE": "Depot",
     "CA": "depòsit"
    },
    {
     "ES (ESP)": "Derecho",
     "ES (ARG)": "Derecho",
     "EN (UK)": "Right",
     "EN (US)": "Right",
     "EN (IR)": "Right",
     "FR": "Droit",
     "IT": "diritto",
     "DE": "Recht",
     "CA": "dret"
    },
    {
     "ES (ESP)": "Derecho de retención",
     "ES (ARG)": "Derecho de retención",
     "EN (UK)": "Lien",
     "EN (US)": "Lien",
     "EN (IR)": "Lien",
     "FR": "Droit de rétention",
     "IT": "diritto di ritenzione",
     "DE": "(Grund)pfandrecht \/ Zurückbehaltungsrecht (auf Waren)",
     "CA": "dret de retenció"
    },
    {
     "ES (ESP)": "Descripción registral\/Referencia registral\/Escritura (pública)\/Registro\/Inscripción (registral)\/Escrituración",
     "ES (ARG)": "Escritura (pública)\/Matrícula\/Registro\/Inscripción (registral)\/Escrituración\/Nomenclatura catastral\/Matriculación",
     "EN (UK)": "Registry description\/Legal description of the property",
     "EN (US)": "Legal description of the property\/Legal land description",
     "EN (IR)": "Registry description",
     "FR": "Description de l'enregistrement de la propriété\/Acte authentique de proprieté\/Enregistrement de la propriété\/Acte notarié\/Registre",
     "IT": "visura catastale",
     "DE": "Grundbucheintragung",
     "CA": "Descripció registral\/referència registral\/Escriptura (pública)\/Registre\/Inscripció(registral)\/Escripturació "
    },
    {
     "ES (ESP)": "Designar",
     "ES (ARG)": "Designar",
     "EN (UK)": "To designate",
     "EN (US)": "To designate",
     "EN (IR)": "To designate",
     "FR": "Désigner",
     "IT": "designare",
     "DE": "ernennen",
     "CA": "designar"
    },
    {
     "ES (ESP)": "Deudor",
     "ES (ARG)": "Deudor",
     "EN (UK)": "Debtor",
     "EN (US)": "Debtor",
     "EN (IR)": "Debtor",
     "FR": "Débiteur",
     "IT": "debitore(-trice)",
     "DE": "Schuldner",
     "CA": "deutor"
    },
    {
     "ES (ESP)": "De una parte… De otra parte…",
     "ES (ARG)": "Entre\/Se reúnen",
     "EN (UK)": "Between",
     "EN (US)": "Between",
     "EN (IR)": "Between",
     "FR": "Entre",
     "IT": "da una parte… dall'altra parte…",
     "DE": "Zwischen",
     "CA": "d'una part\/de l'altra"
    },
    {
     "ES (ESP)": "Diligencia",
     "ES (ARG)": "Diligencia",
     "EN (UK)": "Diligence",
     "EN (US)": "Diligence",
     "EN (IR)": "Diligence",
     "FR": "Diligence",
     "IT": "diligenza",
     "DE": "Sorgfalt",
     "CA": "diligència"
    },
    {
     "ES (ESP)": "Discrepancia",
     "ES (ARG)": "Discrepancia",
     "EN (UK)": "Discrepancy",
     "EN (US)": "Discrepancy",
     "EN (IR)": "Discrepancy",
     "FR": "Désaccord",
     "IT": "discrepanza",
     "DE": "Diskrepanz",
     "CA": "discrepància"
    },
    {
     "ES (ESP)": "Disposición\/Cláusula\/Estipulación",
     "ES (ARG)": "Disposición\/Cláusula\/Estipulación",
     "EN (UK)": "Clause\/provition\/disposition",
     "EN (US)": "Clause\/provition\/disposition",
     "EN (IR)": "Provision",
     "FR": "Clause\/Stipulation\/Disposition",
     "IT": "disposizione\/clausola\/stipulazione",
     "DE": "Klausel \/ Abmachung \/Vereinbarung \/ Bestimmung",
     "CA": "Disposició\/Clàusula\/Estipulació "
    },
    {
     "ES (ESP)": "Documento\/Documentación",
     "ES (ARG)": "Documento\/Documentación",
     "EN (UK)": "Document\/Documentation",
     "EN (US)": "Document\/Documentation",
     "EN (IR)": "Document",
     "FR": "Document\/Documentation",
     "IT": "documento\/documentazione",
     "DE": "Dokument \/ Dokumentation",
     "CA": "document\/documentació"
    },
    {
     "ES (ESP)": "Domicilio",
     "ES (ARG)": "Domicilio",
     "EN (UK)": "Address",
     "EN (US)": "Address",
     "EN (IR)": "Address",
     "FR": "Adresse",
     "IT": "domicilio",
     "DE": "Anschrift \/ Adresse",
     "CA": "domicili"
    },
    {
     "ES (ESP)": "Dominio",
     "ES (ARG)": "Dominio",
     "EN (UK)": "Domain",
     "EN (US)": "Domain",
     "EN (IR)": "Domain",
     "FR": "Domaine",
     "IT": "dominio",
     "DE": "Eigentum \/ Domäne",
     "CA": "domini"
    },
    {
     "ES (ESP)": "Dueño\/Propietario",
     "ES (ARG)": "Dueño\/Propietario",
     "EN (UK)": "Owner\/Landlord",
     "EN (US)": "Owner\/Landlord",
     "EN (IR)": "Owner\/Landlord",
     "FR": "Propriétaire",
     "IT": "titolare\/propietario",
     "DE": "Eigentümer \/ Inhaber \/ Vermieter",
     "CA": "propietari"
    },
    {
     "ES (ESP)": "Ejecutar",
     "ES (ARG)": "Ejecutar",
     "EN (UK)": "To execute",
     "EN (US)": "To execute",
     "EN (IR)": "To execute",
     "FR": "Mettre en oeuvre",
     "IT": "eseguire",
     "DE": "vollstrecken \/ ausführen \/ abwickeln",
     "CA": "executar"
    },
    {
     "ES (ESP)": "Enajenación",
     "ES (ARG)": "Enajenación",
     "EN (UK)": "Alienation (of property)",
     "EN (US)": "Alienation (of property)",
     "EN (IR)": "Alienation (of property)",
     "FR": "Aliénation",
     "IT": "alienazione",
     "DE": "Veräußerung",
     "CA": "alienació"
    },
    {
     "ES (ESP)": "En su propio nombre y derecho",
     "ES (ARG)": "Acredita(n) su identidad",
     "EN (UK)": "In his\/her own name and right",
     "EN (US)": "In his\/her own name and right",
     "EN (IR)": "In his\/her own name and right",
     "FR": "En leur nom propre",
     "IT": "in nome e per conto proprio",
     "DE": "im eigenen Namen",
     "CA": "En el seu propi nom i dret"
    },
    {
     "ES (ESP)": "Escritura",
     "ES (ARG)": "Escritura",
     "EN (UK)": "Deed",
     "EN (US)": "Deed",
     "EN (IR)": "Deed",
     "FR": "Acte",
     "IT": "rogito\/atto di compravendita",
     "DE": "Urkunde",
     "CA": "escriptura"
    },
    {
     "ES (ESP)": "Escritura hipotecaria",
     "ES (ARG)": "Escritura hipotecaria",
     "EN (UK)": "Mortgage deed",
     "EN (US)": "Mortgage deed",
     "EN (IR)": "Mortgage deed",
     "FR": "Acte d'hypothécaire",
     "IT": "rogito del mutuo",
     "DE": "Hypothekurkunde",
     "CA": "escriptura hipotecària"
    },
    {
     "ES (ESP)": "Escritura (pública)\/referencia",
     "ES (ARG)": "Escritura (pública)\/Matrícula\/Registro\/Inscripción (registral)\/Escrituración\/Nomenclatura catastral\/Matriculación",
     "EN (UK)": "Registry description\/Legal description of the property",
     "EN (US)": "Legal description of the property\/Legal land description",
     "EN (IR)": "Registry description",
     "FR": "Acte public",
     "IT": "rogito\/atto di compravendita",
     "DE": "Grundbucheintragung \/ Grundbuchangaben",
     "CA": "escriptura (pública)\/referència "
    },
    {
     "ES (ESP)": "Especial",
     "ES (ARG)": "Especial",
     "EN (UK)": "Special",
     "EN (US)": "Special",
     "EN (IR)": "Special\/Particular",
     "FR": "Spécial\/particulier",
     "IT": "Speciale",
     "DE": "besonder",
     "CA": "especial"
    },
    {
     "ES (ESP)": "Estipulación\/Disposición\/Cláusula",
     "ES (ARG)": "Estipulación\/Disposición\/Cláusula",
     "EN (UK)": "Clause\/provition\/disposition",
     "EN (US)": "Clause\/provition\/disposition",
     "EN (IR)": "Provision",
     "FR": "Clause\/Stipulation\/Disposition",
     "IT": "stipulazione\/disposizione\/clausola",
     "DE": "Klausel \/ Abmachung \/Vereinbarung \/ Bestimmung",
     "CA": "Estipulació\/Disposició\/Clàusula "
    },
    {
     "ES (ESP)": "Entregar",
     "ES (ARG)": "Entregar",
     "EN (UK)": "To delivery\/To transfer",
     "EN (US)": "To delivery\/To transfer",
     "EN (IR)": "To transfer",
     "FR": "Remettre\/Rendre",
     "IT": "trasferire\/cedere",
     "DE": "übergeben",
     "CA": "Lliurar"
    },
    {
     "ES (ESP)": "En virtud de\/Con arreglo a\/Conforme a\/Lo dispuesto en\/Regulado por\/En conformidad con",
     "ES (ARG)": "En virtud de\/Con arreglo a\/Conforme a\/Lo dispuesto en\/Regulado por\/En conformidad con\/Sujección al",
     "EN (UK)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (US)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (IR)": "Pursuant to\/\nIn accordance with\/ \nIn relation to\/",
     "FR": "Conformément à\/Les dispositions\/Réglementée par\/En vertu de",
     "IT": "in base a\/secondo quanto previsto\/secondo quanto stabilito\/in conformità a",
     "DE": "nach Maßgabe von \/ gemäß \/ auf Grund \/ entsprechend den Bestimmungen",
     "CA": "Conforme al\/D'acord amb\/Segons s'estableix\/ segons el que disposa el\/en virtut de "
    },
    {
     "ES (ESP)": "Evicción",
     "ES (ARG)": "Evicción",
     "EN (UK)": "Eviction",
     "EN (US)": "Eviction",
     "EN (IR)": "Eviction",
     "FR": "Éviction",
     "IT": "evizione",
     "DE": "Eviktion \/ (Besitz)entziehung",
     "CA": "evicció"
    },
    {
     "ES (ESP)": "Facultad\/Capacidad",
     "ES (ARG)": "Facultad\/Capacidad",
     "EN (UK)": "Capacity",
     "EN (US)": "Capacity",
     "EN (IR)": "Capacity",
     "FR": "Capacité\/Pouvoir",
     "IT": "facoltà\/capacità",
     "DE": "Rechtsfähigkeit \/ Befügnis",
     "CA": "facultat\/capacitat"
    },
    {
     "ES (ESP)": "Fecha",
     "ES (ARG)": "Fecha",
     "EN (UK)": "Date",
     "EN (US)": "Date",
     "EN (IR)": "Date",
     "FR": "Date",
     "IT": "data",
     "DE": "Datum",
     "CA": "data"
    },
    {
     "ES (ESP)": "Fideicomisario",
     "ES (ARG)": "Fideicomisario",
     "EN (UK)": "Trustee",
     "EN (US)": "Trustee",
     "EN (IR)": "Trustee",
     "FR": "Fidéicommis",
     "IT": "fedecommissario",
     "DE": "Nacherbe \/ Treuhänder \/ Treuhandverwalter",
     "CA": "fideïcomissari"
    },
    {
     "ES (ESP)": "Finca",
     "ES (ARG)": "Finca",
     "EN (UK)": "Estate\/Land",
     "EN (US)": "Estate\/Land",
     "EN (IR)": "Estate\/Land",
     "FR": "Propriété",
     "IT": "terreno\/tenuta",
     "DE": "Grundstück",
     "CA": "finca"
    },
    {
     "ES (ESP)": "Firma",
     "ES (ARG)": "Firma",
     "EN (UK)": "Signature",
     "EN (US)": "Signature",
     "EN (IR)": "Signature",
     "FR": "Signature",
     "IT": "firma",
     "DE": "Unterschrift",
     "CA": "signatura"
    },
    {
     "ES (ESP)": "Formalización",
     "ES (ARG)": "Formalización",
     "EN (UK)": "Execution",
     "EN (US)": "Execution",
     "EN (IR)": "Execution",
     "FR": "Formalisation",
     "IT": "formalizzazione",
     "DE": "öffentliche Beurkundung",
     "CA": "formalització"
    },
    {
     "ES (ESP)": "Folio (registral)",
     "ES (ARG)": "Folio Real",
     "EN (UK)": "Folio",
     "EN (US)": "Folio",
     "EN (IR)": "Folio",
     "FR": "Folio",
     "IT": "foglio (sulla visura)",
     "DE": "Grundbuchblatt",
     "CA": "foli (registral)"
    },
    {
     "ES (ESP)": "Fuero\/Jurisdicción",
     "ES (ARG)": "Fuero\/Jurisdicción",
     "EN (UK)": "Jurisdiction",
     "EN (US)": "Jurisdiction",
     "EN (IR)": "Jurisdiction",
     "FR": "Juricdiction",
     "IT": "giurisdizione",
     "DE": "Gerichtsstand \/ Gerichtsbarkeit",
     "CA": "Fur\/Jurisdicció"
    },
    {
     "ES (ESP)": "Laboral",
     "ES (ARG)": "Laboral",
     "EN (UK)": "Working",
     "EN (US)": "Working",
     "EN (IR)": "Working",
     "FR": "Laboral",
     "IT": "del lavoro",
     "DE": "Arbeit-",
     "CA": "laboral"
    },
    {
     "ES (ESP)": "Legal",
     "ES (ARG)": "Legal",
     "EN (UK)": "Legal",
     "EN (US)": "Legal",
     "EN (IR)": "Legal",
     "FR": "Légal",
     "IT": "legale",
     "DE": "gesetzlich",
     "CA": "legal"
    },
    {
     "ES (ESP)": "Legitimación",
     "ES (ARG)": "Legitimación",
     "EN (UK)": "Legitimacy",
     "EN (US)": "Legitimacy",
     "EN (IR)": "Legitimacy",
     "FR": "Légitimation",
     "IT": "legittimizzazione",
     "DE": "Legitimation",
     "CA": "legitimació"
    },
    {
     "ES (ESP)": "Ley",
     "ES (ARG)": "Ley",
     "EN (UK)": "Act\/Statute",
     "EN (US)": "Act\/Statute",
     "EN (IR)": "Act",
     "FR": "Loi",
     "IT": "legge",
     "DE": "Gesetz",
     "CA": "llei"
    },
    {
     "ES (ESP)": "Libre (sin cargos)",
     "ES (ARG)": "Libre (sin cargos)",
     "EN (UK)": "Unencumbered\/Free and clear",
     "EN (US)": "Unencumbered\/Free and clear",
     "EN (IR)": "Encumbered\/\nVacant",
     "FR": "Libre de toute charge",
     "IT": "libero (da pesi\/da oneri)",
     "DE": "lastenfrei",
     "CA": "lliure (de càrrecs)"
    },
    {
     "ES (ESP)": "Litigio\/Controversia",
     "ES (ARG)": "Litigio\/Controversia",
     "EN (UK)": "Dispute",
     "EN (US)": "Dispute",
     "EN (IR)": "Dispute",
     "FR": "Controverse\/Litige",
     "IT": "causa\/controversia",
     "DE": "Streit \/ Streitfall \/Streitigkeit",
     "CA": "litigi\/controvèrsia"
    },
    {
     "ES (ESP)": "Lo dispuesto en\/En virtud de\/Con arregloa \/Conforme a\/Regulado por\/De conformidad con",
     "ES (ARG)": "En virtud de\/Con arreglo a\/Conforme a\/Lo dispuesto en\/Regulado por\/En conformidad con\/Sujección al",
     "EN (UK)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (US)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (IR)": "Pursuant to\/\nIn accordance with\/ \nIn relation to\/",
     "FR": "Conformément à\/Les dispositions\/Réglementée par\/En vertu de",
     "IT": "in base a\/secondo quanto previsto\/secondo quanto stabilito\/in conformità a",
     "DE": "nach Maßgabe von \/ gemäß \/ auf Grund \/ entsprechend den Bestimmungen",
     "CA": "Conforme al\/D'acord amb\/Segons s'estableix\/ segons el que disposa el\/en virtut de "
    },
    {
     "ES (ESP)": "Garantía\/Seguro",
     "ES (ARG)": "Garantía\/Seguro",
     "EN (UK)": "Warrant\/Assurance",
     "EN (US)": "Warrant\/Assurance",
     "EN (IR)": "Warrant\/\nAssurance\/\nInsurance",
     "FR": "Garantie\/Assurance",
     "IT": "garanzia\/assicurazione",
     "DE": "Haftung \/ Gewährleistung \/ Sicherung",
     "CA": "Garantia\/Assegurança"
    },
    {
     "ES (ESP)": "Gasto",
     "ES (ARG)": "Gasto",
     "EN (UK)": "Expense",
     "EN (US)": "Expense",
     "EN (IR)": "Expense\/\nOutgoings\/\nOutlay",
     "FR": "Dépense",
     "IT": "spesa",
     "DE": "Ausgabe",
     "CA": "despesa"
    },
    {
     "ES (ESP)": "General",
     "ES (ARG)": "General",
     "EN (UK)": "General",
     "EN (US)": "General",
     "EN (IR)": "General",
     "FR": "Général",
     "IT": "generale",
     "DE": "allgemein",
     "CA": "general"
    },
    {
     "ES (ESP)": "Gravamen",
     "ES (ARG)": "Gravamen",
     "EN (UK)": "Encumbrance",
     "EN (US)": "Encumbrance",
     "EN (IR)": "Charge",
     "FR": "Taxe",
     "IT": "gravame",
     "DE": "Last",
     "CA": "Gravamen\/càrrega"
    },
    {
     "ES (ESP)": "Hipoteca",
     "ES (ARG)": "Hipoteca",
     "EN (UK)": "Mortgage",
     "EN (US)": "Mortgage",
     "EN (IR)": "Mortgage",
     "FR": "Crédit immobilier",
     "IT": "mutuo",
     "DE": "Hypothek",
     "CA": "hipoteca"
    },
    {
     "ES (ESP)": "Importe\/Cantidad\/Monto\/Suma\/Cuantía",
     "ES (ARG)": "Importe\/Cantidad\/Monto\/Suma\/Cuantía",
     "EN (UK)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (US)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (IR)": "Amount",
     "FR": "Quantité\/Montant\/Somme",
     "IT": "importo\/quantità\/somma",
     "DE": "Betrag \/ Geldbetrag \/ Gesamtbetrag \/ Geldsumme \/ Summe",
     "CA": "Import\/Quantitat\/Suma\/Quantia "
    },
    {
     "ES (ESP)": "Imprudencia",
     "ES (ARG)": "Imprudencia",
     "EN (UK)": "Recklessness",
     "EN (US)": "Recklessness",
     "EN (IR)": "Recklessness",
     "FR": "Imprudence",
     "IT": "imprudenza",
     "DE": "Fahrlässigkeit",
     "CA": "imprudència"
    },
    {
     "ES (ESP)": "Impuesto",
     "ES (ARG)": "Impuesto",
     "EN (UK)": "Tax\/Taxation\/Fee",
     "EN (US)": "Tax\/Taxation\/Fee",
     "EN (IR)": "Tax\/\nTaxation",
     "FR": "Impôt",
     "IT": "imposta\/tassa",
     "DE": "Steuer",
     "CA": "impost"
    },
    {
     "ES (ESP)": "Incumplimiento",
     "ES (ARG)": "Incumplimiento",
     "EN (UK)": "Breach",
     "EN (US)": "Breach",
     "EN (IR)": "Breach",
     "FR": "Non-exécution",
     "IT": "inadempienza",
     "DE": "Nichterfüllung",
     "CA": "incumpliment"
    },
    {
     "ES (ESP)": "Indemnización",
     "ES (ARG)": "Indemnización",
     "EN (UK)": "Compensation",
     "EN (US)": "Compensation",
     "EN (IR)": "Compensation\/\nReparation",
     "FR": "Indemnité",
     "IT": "indennizzo\/risarcimento",
     "DE": "Entschädigung",
     "CA": "indemnització"
    },
    {
     "ES (ESP)": "Inmueble",
     "ES (ARG)": "Inmueble",
     "EN (UK)": "House\/Real estate\/Dwelling",
     "EN (US)": "House\/Real estate\/Dwelling",
     "EN (IR)": "House\/\nReal estate\/\nDwelling",
     "FR": "Inmeuble\/Bâtiment",
     "IT": "immobile",
     "DE": "Grundstück",
     "CA": "inmoble"
    },
    {
     "ES (ESP)": "Inquilino\/Arrendatario",
     "ES (ARG)": "Inquilino\/Arrendatario\/Locatario",
     "EN (UK)": "Tenant\/Lessee\/Leaseholder",
     "EN (US)": "Tenant\/Lessee\/Leaseholder",
     "EN (IR)": "Tenant",
     "FR": "Locataire",
     "IT": "inquilino(-a)\/locatario(-a)",
     "DE": "Mieter \/ Pächter",
     "CA": "llogater\/arrendatari"
    },
    {
     "ES (ESP)": "Inscripción (registral)\/Referencia registral\/Descripción registral\/Escritura (pública)\/Registro\/Escrituración",
     "ES (ARG)": "Escritura (pública)\/Matrícula\/Registro\/Inscripción (registral)\/Escrituración\/Nomenclatura catastral\/Matriculación",
     "EN (UK)": "Registry description\/Legal description of the property",
     "EN (US)": "Legal description of the property\/Legal land description",
     "EN (IR)": "Registry description",
     "FR": "Description de l'enregistrement de la propriété\/Acte authentique de proprieté\/Enregistrement de la propriété\/Acte notarié\/Registre",
     "IT": "visura catastale",
     "DE": "Grundbucheintragung \/ Grundbuchangaben",
     "CA": "Descripció registral\/referència registral\/Escriptura (pública)\/Registre\/Inscripció(registral)\/Escripturació "
    },
    {
     "ES (ESP)": "Inspección",
     "ES (ARG)": "Inspección",
     "EN (UK)": "Inspection",
     "EN (US)": "Inspection",
     "EN (IR)": "Inspection",
     "FR": "Inspection",
     "IT": "ispezione",
     "DE": "Inspektion \/ Prüfung",
     "CA": "inspecció"
    },
    {
     "ES (ESP)": "Instancia",
     "ES (ARG)": "Instancia",
     "EN (UK)": "Instance",
     "EN (US)": "Instance",
     "EN (IR)": "Instance",
     "FR": "Instance",
     "IT": "istanza",
     "DE": "Instanz",
     "CA": "instància"
    },
    {
     "ES (ESP)": "Interés",
     "ES (ARG)": "Interés",
     "EN (UK)": "Interest",
     "EN (US)": "Interest",
     "EN (IR)": "Interest",
     "FR": "Intérêt",
     "IT": "interesse",
     "DE": "Interesse \/ Zinsen",
     "CA": "interés"
    },
    {
     "ES (ESP)": "Intervienen\/Reunidos\/Comparecen",
     "ES (ARG)": "Entre\/Se reúnen",
     "EN (UK)": "Between",
     "EN (US)": "Between",
     "EN (IR)": "Between",
     "FR": "Entre\/Entre les sousignés",
     "IT": "intervengono\/riuniti\/compariscono",
     "DE": "zwischen",
     "CA": "Intervenen\/Reunits\/Compareixen "
    },
    {
     "ES (ESP)": "Jurisdicción\/Fuero",
     "ES (ARG)": "Jurisdicción\/Fuero",
     "EN (UK)": "Jurisdiction",
     "EN (US)": "Jurisdiction",
     "EN (IR)": "Jurisdiction",
     "FR": "Juricdiction",
     "IT": "giurisdizione",
     "DE": "Gerichtsstand \/ Gerichtsbarkeit",
     "CA": "Jurisdicció\/"
    },
    {
     "ES (ESP)": "Límite",
     "ES (ARG)": "Límite",
     "EN (UK)": "Limit",
     "EN (US)": "Limit",
     "EN (IR)": "Limit",
     "FR": "Limite",
     "IT": "limite",
     "DE": "Grenze",
     "CA": "límit"
    },
    {
     "ES (ESP)": "Mutuo acuerdo",
     "ES (ARG)": "Mutuo acuerdo\/Común y mutuo acuerdo",
     "EN (UK)": "Mutual consent\/Mutually agreed",
     "EN (US)": "Mutual consent\/Mutually agreed",
     "EN (IR)": "Mutual agreement",
     "FR": "Commun accord",
     "IT": "mutuo accordo",
     "DE": "(durch) beiderseitiges Abkommen",
     "CA": "Mutu acord"
    },
    {
     "ES (ESP)": "Normativa\/Prescripciones legales",
     "ES (ARG)": "Normativa",
     "EN (UK)": "Regulations\/Rules",
     "EN (US)": "Regulations\/Rules",
     "EN (IR)": "Regulations",
     "FR": "Réglementation\/Prescriptin légale",
     "IT": "normativa\/prescrizioni legali",
     "DE": "Vorschriften",
     "CA": "Normativa\/ Condicions legals "
    },
    {
     "ES (ESP)": "Notario (público)",
     "ES (ARG)": "Notario (público)\/Escribano (público)",
     "EN (UK)": "Notary\/Notary Public",
     "EN (US)": "Notary\/Notary Public",
     "EN (IR)": "Notary",
     "FR": "Notaire",
     "IT": "(pubblico) notaio",
     "DE": "Notar",
     "CA": "notari (públic)"
    },
    {
     "ES (ESP)": "Notificación\/Comunicación",
     "ES (ARG)": "Notificación\/Comunicación",
     "EN (UK)": "Notice\/Communication",
     "EN (US)": "Notice\/Communication",
     "EN (IR)": "Notice\/Communication",
     "FR": "Communication\/Avis\/Préavis\/Notification",
     "IT": "notifica\/comunicazione",
     "DE": "Mitteilung \/ Benachrigtigung \/ Zustellung",
     "CA": "notificació\/comunicació"
    },
    {
     "ES (ESP)": "Obligación\/Responsabilidad",
     "ES (ARG)": "Obligación\/Responsabilidad",
     "EN (UK)": "Obligation\/Responsability\/Liability",
     "EN (US)": "Obligation\/Responsability\/Liability",
     "EN (IR)": "Obligation\/\nLiability",
     "FR": "Obligation\/Responsabilité",
     "IT": "obbligazione",
     "DE": "Pflicht \/ Haftpflicht",
     "CA": "obligació\/responsabilitat"
    },
    {
     "ES (ESP)": "Ocupación",
     "ES (ARG)": "Ocupación",
     "EN (UK)": "Occupation\/Occupancy",
     "EN (US)": "Occupation\/Occupancy",
     "EN (IR)": "Occupation",
     "FR": "Occupation (de logement)",
     "IT": "occupazione",
     "DE": "Bewohnen",
     "CA": "ocupació"
    },
    {
     "ES (ESP)": "Ocupante",
     "ES (ARG)": "Ocupante\/Intruso",
     "EN (UK)": "Occupier",
     "EN (US)": "Occupier",
     "EN (IR)": "Occupier",
     "FR": "Occupant",
     "IT": "occupante",
     "DE": "Bewohner",
     "CA": "ocupant"
    },
    {
     "ES (ESP)": "Otorgamiento",
     "ES (ARG)": "Otorgamiento",
     "EN (UK)": "Grant",
     "EN (US)": "Grant",
     "EN (IR)": "Grant",
     "FR": "Autorisation",
     "IT": "concessione",
     "DE": "Erteilung",
     "CA": "atorgament"
    },
    {
     "ES (ESP)": "Pacto\/Acuerdo",
     "ES (ARG)": "Pacto\/Acuerdo",
     "EN (UK)": "Covenant",
     "EN (US)": "Covenant",
     "EN (IR)": "Covenant",
     "FR": "Accord\/Pacte",
     "IT": "patto\/accordo",
     "DE": "Abkommen \/ Vertrag",
     "CA": "pacte\/acord"
    },
    {
     "ES (ESP)": "Pagadero",
     "ES (ARG)": "Pagadero",
     "EN (UK)": "Payable",
     "EN (US)": "Payable",
     "EN (IR)": "Payable",
     "FR": "Payable",
     "IT": "pagabile",
     "DE": "fällig",
     "CA": "pagable"
    },
    {
     "ES (ESP)": "Pago",
     "ES (ARG)": "Pago",
     "EN (UK)": "Payment",
     "EN (US)": "Payment",
     "EN (IR)": "Payment",
     "FR": "Paiement",
     "IT": "pagamento",
     "DE": "Zahlung",
     "CA": "pagament"
    },
    {
     "ES (ESP)": "Pareja civil (de hecho)",
     "ES (ARG)": "Unión civil\/convivencial",
     "EN (UK)": "Civil Partner",
     "EN (US)": "Civil Partner",
     "EN (IR)": "Civil Partner",
     "FR": "Couple pacsé",
     "IT": "coppia di fatto",
     "DE": "eingetragene Partnerschaft",
     "CA": "parella civil (de fet)"
    },
    {
     "ES (ESP)": "Parte",
     "ES (ARG)": "Parte",
     "EN (UK)": "Party",
     "EN (US)": "Party",
     "EN (IR)": "Party",
     "FR": "Part",
     "IT": "parte",
     "DE": "Partei",
     "CA": "part"
    },
    {
     "ES (ESP)": "Parte compradora\/Adquiriente\/Comprador",
     "ES (ARG)": "Parte vendedora\/Vendedor\/Dador",
     "EN (UK)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "EN (US)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "EN (IR)": "Acquirer [not very frequently]\/Buyer\/Purchaser",
     "FR": "Acquéreur\/Acheteur\/Acquéreur",
     "IT": "parte compratrice\/acquirente\/compratore",
     "DE": "Käufer \/ Erwerber \/ Abnehmer",
     "CA": "part compradora\/comprador "
    },
    {
     "ES (ESP)": "Parte vendedora\/Vendedor",
     "ES (ARG)": "Parte vendedora\/Vendedor",
     "EN (UK)": "Seller",
     "EN (US)": "Seller",
     "EN (IR)": "Seller",
     "FR": "Vendeur",
     "IT": "parte venditrice\/venditore",
     "DE": "Verkäufer",
     "CA": "part venedora\/venedor"
    },
    {
     "ES (ESP)": "Particular",
     "ES (ARG)": "Particular",
     "EN (UK)": "Particular",
     "EN (US)": "Particular",
     "EN (IR)": "Particular\/Special",
     "FR": "Particulier",
     "IT": "particolare",
     "DE": "Privatperson",
     "CA": "particular"
    },
    {
     "ES (ESP)": "Pecuniario",
     "ES (ARG)": "Pecuniario",
     "EN (UK)": "Pecuniary",
     "EN (US)": "Pecuniary",
     "EN (IR)": "Pecuniary",
     "FR": "Pécuniaire",
     "IT": "pecuniario",
     "DE": "Geld- \/ geldlich",
     "CA": "pecuniari"
    },
    {
     "ES (ESP)": "Pérdida",
     "ES (ARG)": "Pérdida",
     "EN (UK)": "Loss",
     "EN (US)": "Loss",
     "EN (IR)": "Loss",
     "FR": "Perte",
     "IT": "perdita",
     "DE": "Verlust",
     "CA": "pèrdua"
    },
    {
     "ES (ESP)": "Periodo",
     "ES (ARG)": "Periodo",
     "EN (UK)": "Period",
     "EN (US)": "Period",
     "EN (IR)": "Period",
     "FR": "Période",
     "IT": "periodo",
     "DE": "Zeitraum",
     "CA": "periode"
    },
    {
     "ES (ESP)": "Plazo",
     "ES (ARG)": "Plazo",
     "EN (UK)": "Term",
     "EN (US)": "Term",
     "EN (IR)": "Term",
     "FR": "Délai",
     "IT": "scadenza",
     "DE": "Frist",
     "CA": "termini"
    },
    {
     "ES (ESP)": "Pleno dominio",
     "ES (ARG)": "Pleno\/Perfecto dominio",
     "EN (UK)": "Freehold",
     "EN (US)": "Freehold",
     "EN (IR)": "Freehold",
     "FR": "Pleine maîtrise",
     "IT": "pieno dominio",
     "DE": "Volleigentum",
     "CA": "ple domini"
    },
    {
     "ES (ESP)": "Posesión",
     "ES (ARG)": "Posesión",
     "EN (UK)": "Possession",
     "EN (US)": "Possession",
     "EN (IR)": "Possession",
     "FR": "Possession",
     "IT": "proprietà\/possesso\/avere",
     "DE": "Besitz",
     "CA": "posesió"
    },
    {
     "ES (ESP)": "Precio (de venta)",
     "ES (ARG)": "Precio (de venta)",
     "EN (UK)": "Price\/Sale price",
     "EN (US)": "Price\/Sale price",
     "EN (IR)": "Price\/Sale price",
     "FR": "Prix (de vente)",
     "IT": "prezzo (di vendita)",
     "DE": "Preis \/ Kaufpreis",
     "CA": "preu (de venda)"
    },
    {
     "ES (ESP)": "Presente",
     "ES (ARG)": "Presente",
     "EN (UK)": "Present",
     "EN (US)": "Present",
     "EN (IR)": "Present",
     "FR": "Présent",
     "IT": "presente",
     "DE": "gegenwärtig",
     "CA": "present"
    },
    {
     "ES (ESP)": "Prescipciones legales\/Normativa",
     "ES (ARG)": "Normativa",
     "EN (UK)": "Regulations\/Rules",
     "EN (US)": "Regulations\/Rules",
     "EN (IR)": "Regulations",
     "FR": "Prescription légale\/Réglementation",
     "IT": "normativa\/prescrizioni legali",
     "DE": "Vorschriften",
     "CA": "Condicions legals\/Normativa "
    },
    {
     "ES (ESP)": "Prestamista",
     "ES (ARG)": "Prestamista",
     "EN (UK)": "Lender",
     "EN (US)": "Lender",
     "EN (IR)": "Lender",
     "FR": "Prêteur",
     "IT": "usuraio\/prestatore(-trice)",
     "DE": "Darlehensgeber",
     "CA": "prestador"
    },
    {
     "ES (ESP)": "Préstamo",
     "ES (ARG)": "Préstamo",
     "EN (UK)": "Loan",
     "EN (US)": "Loan",
     "EN (IR)": "Loan",
     "FR": "Crédit",
     "IT": "prestito",
     "DE": "Darlehen",
     "CA": "prèstec"
    },
    {
     "ES (ESP)": "Previo",
     "ES (ARG)": "Previo",
     "EN (UK)": "Prior",
     "EN (US)": "Prior",
     "EN (IR)": "Prior",
     "FR": "Préalable",
     "IT": "previo",
     "DE": "vorherig",
     "CA": "previ"
    },
    {
     "ES (ESP)": "Propiedad",
     "ES (ARG)": "Propiedad",
     "EN (UK)": "Property",
     "EN (US)": "Property",
     "EN (IR)": "Property",
     "FR": "Propriété",
     "IT": "proprietà\/possesso\/avere",
     "DE": "Eigentum",
     "CA": "propietat"
    },
    {
     "ES (ESP)": "Propiedad comunitaria\/Copropiedad\/Condominio",
     "ES (ARG)": "Propiedad comunitaria\/Copropiedad\/Condominio",
     "EN (UK)": "Condominium",
     "EN (US)": "Condominium",
     "EN (IR)": "Condominium",
     "FR": "Copropriété",
     "IT": "proprietà condominiale\/comproprietà",
     "DE": "Miteigentum \/ Gemeinschaftsbesitz \/Gemeischaftseigentum",
     "CA": "Propietat comunitària\/copropietat\/ condomini "
    },
    {
     "ES (ESP)": "Propietario\/Dueño",
     "ES (ARG)": "Propietario\/Dueño",
     "EN (UK)": "Owner\/Landlord",
     "EN (US)": "Owner\/Landlord",
     "EN (IR)": "Owner\/Landlord",
     "FR": "Propriétaire",
     "IT": "propietario(-a)\/titolare",
     "DE": "Eigentümer \/ Besitzer \/ Vermieter",
     "CA": "propietari"
    },
    {
     "ES (ESP)": "Prorrateo",
     "ES (ARG)": "Prorrateo",
     "EN (UK)": "Apportionment",
     "EN (US)": "Apportionment",
     "EN (IR)": "Apportionment",
     "FR": "Partage",
     "IT": "ripartizione\/distribuzione\/assegnazione",
     "DE": "Aufteilung",
     "CA": "prorrateig"
    },
    {
     "ES (ESP)": "Prórroga",
     "ES (ARG)": "Prórroga",
     "EN (UK)": "Extension",
     "EN (US)": "Extension",
     "EN (IR)": "Extension",
     "FR": "Report",
     "IT": "proroga",
     "DE": "Verlängerung",
     "CA": "pròrroga"
    },
    {
     "ES (ESP)": "Prueba",
     "ES (ARG)": "Prueba",
     "EN (UK)": "Evidence",
     "EN (US)": "Evidence\/Proof",
     "EN (IR)": "Evidence",
     "FR": "Preuve\/Justificatif",
     "IT": "prova",
     "DE": "Beweis",
     "CA": "prova"
    },
    {
     "ES (ESP)": "Público",
     "ES (ARG)": "Público",
     "EN (UK)": "Public",
     "EN (US)": "Public",
     "EN (IR)": "Public",
     "FR": "Public",
     "IT": "pubblico",
     "DE": "öffentlich",
     "CA": "públic"
    },
    {
     "ES (ESP)": "Referencia registral\/Descripción registral\/Escritura (pública)\/Escrituración\/Registro\/Inscripción (registral)",
     "ES (ARG)": "Escritura (pública)\/Matrícula\/Registro\/Inscripción (registral)\/Escrituración\/Nomenclatura catastral\/Matriculación",
     "EN (UK)": "Registry description\/Legal description of the property",
     "EN (US)": "Legal description of the property\/Legal land description",
     "EN (IR)": "Registry description",
     "FR": "Description de l'enregistrement de la propriété\/Acte authentique de proprieté\/Enregistrement de la propriété\/Acte notarié\/Registre",
     "IT": "visura catastale",
     "DE": "Grundbucheintragung \/ Grundbuchangaben",
     "CA": "Referència registral\/Descripció registral\/Escriptura (pública)\/Escripturació\/ Registre\/Inscripció (registral) "
    },
    {
     "ES (ESP)": "Registro de la propiedad\/Catastro",
     "ES (ARG)": "Registro de la Propiedad\/Registro de la Propiedad Inmueble",
     "EN (UK)": "Land registry\/Local deeds registry",
     "EN (US)": "Real Property Official Record",
     "EN (IR)": "Land Registry",
     "FR": "Enregistrement de la propriété\/Cadastre",
     "IT": "catasto\/registro immobiliare",
     "DE": "Grundstücksregister \/ Kataster",
     "CA": "registre de la propietat\/cadastre "
    },
    {
     "ES (ESP)": "Regulado por\/Lo dispuesto en\/En virtud de\/Con arreglo a\/Conforme a\/De conformidad con",
     "ES (ARG)": "Regulado por\/Lo dispuesto en\/En virtud de\/Con arreglo a\/Conforme a\/De conformidad con\/Sujección al",
     "EN (UK)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (US)": "Pursuant to\/In accordance with\/In relation to\/According to",
     "EN (IR)": "Pursuant to\/\nIn accordance with\/ \nIn relation to\/",
     "FR": "Conformément à\/Les dispositions\/Réglementée par\/En vertu de",
     "IT": "in base a\/secondo quanto previsto\/secondo quanto stabilito\/in conformità a",
     "DE": "nach Maßgabe von \/ gemäß \/ auf Grund \/ entsprechend den Bestimmungen",
     "CA": "Regulat per\/El disposat a\/En virtut de\/Conformement a\/de conformitat\/Conforme a "
    },
    {
     "ES (ESP)": "Reparación",
     "ES (ARG)": "Reparación",
     "EN (UK)": "Compensation",
     "EN (US)": "Compensation",
     "EN (IR)": "Compensation\/\nReparation",
     "FR": "Réparation",
     "IT": "riparazione",
     "DE": "Entschädigung \/ Wiedergutmachung",
     "CA": "reparació"
    },
    {
     "ES (ESP)": "Representante",
     "ES (ARG)": "Representante",
     "EN (UK)": "Agent",
     "EN (US)": "Agent",
     "EN (IR)": "Agent",
     "FR": "Représentant",
     "IT": "rappresentante",
     "DE": "Agent",
     "CA": "representant"
    },
    {
     "ES (ESP)": "Requerimiento",
     "ES (ARG)": "Requerimiento",
     "EN (UK)": "Request\/Demand",
     "EN (US)": "Request\/Demand",
     "EN (IR)": "Request\/Demand",
     "FR": "Injonction\/Mise de demeure",
     "IT": "richiesta",
     "DE": "Mahnung \/ Aufforderung",
     "CA": "requeriment"
    },
    {
     "ES (ESP)": "Requisito\/Condición",
     "ES (ARG)": "Requisito\/Condición",
     "EN (UK)": "Condition\/Requirement",
     "EN (US)": "Condition\/Requirement",
     "EN (IR)": "Condition",
     "FR": "Condition\/Exigence",
     "IT": "requisito\/condizione",
     "DE": "Voraussetzung \/ Vorbedingung \/ Erfordernis",
     "CA": "requisit\/condició"
    },
    {
     "ES (ESP)": "Respuesta\/Contestación",
     "ES (ARG)": "Respuesta",
     "EN (UK)": "Reply",
     "EN (US)": "Reply",
     "EN (IR)": "Rejoinder\/\nReply",
     "FR": "Réponse",
     "IT": "risposta",
     "DE": "Antwort",
     "CA": "resposta\/contestació"
    },
    {
     "ES (ESP)": "Rescindir",
     "ES (ARG)": "Rescindir",
     "EN (UK)": "To rescind",
     "EN (US)": "To rescind",
     "EN (IR)": "To rescind",
     "FR": "Résilier",
     "IT": "rescindere",
     "DE": "auflösen",
     "CA": "rescindir"
    },
    {
     "ES (ESP)": "Responsabilidad\/Obligación",
     "ES (ARG)": "Responsabilidad\/Obligación",
     "EN (UK)": "Obligation\/Responsability\/Liability",
     "EN (US)": "Obligation\/Responsability\/Liability",
     "EN (IR)": "Obligation\/\nLiability",
     "FR": "Responsabilité",
     "IT": "obbligazione",
     "DE": "Pflicht \/ Haftpflicht",
     "CA": "responsabilitat\/obligació"
    },
    {
     "ES (ESP)": "Resolución",
     "ES (ARG)": "Resolución",
     "EN (UK)": "Resolution",
     "EN (US)": "Resolution",
     "EN (IR)": "Resolution",
     "FR": "Résolution",
     "IT": "Risoluzione",
     "DE": "Beschluss \/ Urteil \/ Abkommen",
     "CA": "resolució"
    },
    {
     "ES (ESP)": "Retención",
     "ES (ARG)": "Retención",
     "EN (UK)": "Withholding",
     "EN (US)": "Withholding",
     "EN (IR)": "Withholding",
     "FR": "Retenue",
     "IT": "ritenuta",
     "DE": "Zurückbehaltung",
     "CA": "retenció"
    },
    {
     "ES (ESP)": "Reunidos\/Intervienen\/Comparecen",
     "ES (ARG)": "Entre\/Se reúnen",
     "EN (UK)": "Between",
     "EN (US)": "Between",
     "EN (IR)": "Between",
     "FR": "Entre\/Entre les sousignés",
     "IT": "riuniti\/intervengono\/compariscono",
     "DE": "zwischen",
     "CA": "Reunits\/Intervenen\/Compareixen "
    },
    {
     "ES (ESP)": "Sanción",
     "ES (ARG)": "Sanción",
     "EN (UK)": "Penalty",
     "EN (US)": "Penalty",
     "EN (IR)": "Penalty",
     "FR": "Sanction",
     "IT": "sanzione",
     "DE": "Strafe",
     "CA": "sanció"
    },
    {
     "ES (ESP)": "Seguro\/Garantía",
     "ES (ARG)": "Garantía",
     "EN (UK)": "Warrant\/Assurance",
     "EN (US)": "Warrant\/Assurance",
     "EN (IR)": "Warrant\/\nAssurance\/\nInsurance",
     "FR": "Garantie\/Assurance",
     "IT": "assicurazione\/garanzia",
     "DE": "Haftung \/ Gewährleistung \/ Sicherung",
     "CA": "Assegurança\/Garantia"
    },
    {
     "ES (ESP)": "Señal\/Arras",
     "ES (ARG)": "Señal\/Arras",
     "EN (UK)": "Down-payment",
     "EN (US)": "Down-payment",
     "EN (IR)": "Down-payment",
     "FR": "Acompte\/Arrhes",
     "IT": "caparra",
     "DE": "Draufgabe \/ Vorauszahlung",
     "CA": "paga i senyal\/arres"
    },
    {
     "ES (ESP)": "Servidumbre",
     "ES (ARG)": "Servidumbre",
     "EN (UK)": "Easement",
     "EN (US)": "Easement",
     "EN (IR)": "Servidumbre",
     "FR": "Servitude",
     "IT": "servitù",
     "DE": "Dienstbarkeit",
     "CA": "servitud"
    },
    {
     "ES (ESP)": "Subasta",
     "ES (ARG)": "Subasta",
     "EN (UK)": "Auction",
     "EN (US)": "Auction",
     "EN (IR)": "Auction",
     "FR": "Vente aux enchères",
     "IT": "asta",
     "DE": "Versteigerung",
     "CA": "subhasta"
    },
    {
     "ES (ESP)": "Sujeto",
     "ES (ARG)": "Sujeto",
     "EN (UK)": "Subject",
     "EN (US)": "Subject",
     "EN (IR)": "Subject",
     "FR": "Sujet",
     "IT": "soggetto",
     "DE": "Person",
     "CA": "subjecte"
    },
    {
     "ES (ESP)": "Suma\/Cantidad\/Importe\/Monto\/Cuantía",
     "ES (ARG)": "Suma\/Cantidad\/Importe\/Monto\/Cuantía",
     "EN (UK)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (US)": "Total (amount)\/Total (sum)\/Quantity",
     "EN (IR)": "Amount",
     "FR": "Quantité\/Montant\/Somme",
     "IT": "somma\/quantità\/importo",
     "DE": "Betrag \/ Geldbetrag \/ Gesamtbetrag \/ Geldsumme \/ Summe",
     "CA": "Suma\/Quantitat\/Import\/Quantia\/ "
    },
    {
     "ES (ESP)": "Tasación",
     "ES (ARG)": "Tasación",
     "EN (UK)": "Appraisal",
     "EN (US)": "Appraisal",
     "EN (IR)": "Appraisal",
     "FR": "Taxation",
     "IT": "valutazione",
     "DE": "Schätzung",
     "CA": "taxació"
    },
    {
     "ES (ESP)": "Tenencia",
     "ES (ARG)": "Tenencia",
     "EN (UK)": "Tenure",
     "EN (US)": "Tenure",
     "EN (IR)": "Tenure",
     "FR": "Détention\/Posséssion",
     "IT": "possesso",
     "DE": "unmittelbarer Besitz",
     "CA": "tinença"
    },
    {
     "ES (ESP)": "Terminación",
     "ES (ARG)": "Terminación",
     "EN (UK)": "Termination\/Completion",
     "EN (US)": "Termination\/Completion",
     "EN (IR)": "Termination",
     "FR": "Résiliation du contrat",
     "IT": "termine\/compimento",
     "DE": "Ende",
     "CA": "terminació"
    },
    {
     "ES (ESP)": "Testigo",
     "ES (ARG)": "Testigo",
     "EN (UK)": "Witness",
     "EN (US)": "Witness",
     "EN (IR)": "Witness",
     "FR": "Temoin",
     "IT": "testimone",
     "DE": "Zeuge",
     "CA": "testimoni"
    },
    {
     "ES (ESP)": "Título",
     "ES (ARG)": "Título",
     "EN (UK)": "Title",
     "EN (US)": "Title",
     "EN (IR)": "Title",
     "FR": "Titre",
     "IT": "titolo",
     "DE": "Titel",
     "CA": "títol"
    },
    {
     "ES (ESP)": "Transmisión",
     "ES (ARG)": "Transmisión",
     "EN (UK)": "Transmission",
     "EN (US)": "Transmission",
     "EN (IR)": "Transmission",
     "FR": "Transfert",
     "IT": "transmissione",
     "DE": "Übertragung",
     "CA": "transmisió"
    },
    {
     "ES (ESP)": "Tribunal",
     "ES (ARG)": "Tribunal",
     "EN (UK)": "Court",
     "EN (US)": "Court",
     "EN (IR)": "Court",
     "FR": "Cour",
     "IT": "tribunale",
     "DE": "Gericht",
     "CA": "tribunal"
    },
    {
     "ES (ESP)": "Uso y costumbre",
     "ES (ARG)": "Uso y costumbre\/Uso, prácticas y costumbres",
     "EN (UK)": "Usage and custom",
     "EN (US)": "Usage and custom",
     "EN (IR)": "Urban",
     "FR": "L'usage et la costume",
     "IT": "usi e costumi",
     "DE": "Sitten und Gebräuche",
     "CA": "Ús i costum"
    },
    {
     "ES (ESP)": "Urbano",
     "ES (ARG)": "Urbano",
     "EN (UK)": "Urban",
     "EN (US)": "Urban",
     "EN (IR)": "Urbain",
     "FR": "urbano",
     "IT": "städtisch",
     "DE": "urbà"
    },
    {
     "ES (ESP)": "Vencimiento",
     "ES (ARG)": "Vencimiento",
     "EN (UK)": "Expiration",
     "EN (US)": "Expiration",
     "EN (IR)": "Termination",
     "FR": "Échéance",
     "IT": "scadenza",
     "DE": "Ablauf",
     "CA": "venciment"
    },
    {
     "ES (ESP)": "Vendedor\/Parte vendedora",
     "ES (ARG)": "Vendedor\/Parte vendedora\/Dador",
     "EN (UK)": "Vendor",
     "EN (US)": "Vendor",
     "EN (IR)": "Vendor",
     "FR": "Vendeur",
     "IT": "venditore(-trice)\/parte venditrice",
     "DE": "Verkäufer",
     "CA": "venedor\/part venedora"
    },
    {
     "ES (ESP)": "Vender",
     "ES (ARG)": "Vender",
     "EN (UK)": "To sell",
     "EN (US)": "To sell",
     "EN (IR)": "To sell",
     "FR": "Vendre",
     "IT": "vendere",
     "DE": "verkaufen",
     "CA": "vendre"
    },
    {
     "ES (ESP)": "Venta a crédito",
     "ES (ARG)": "Venta a crédito",
     "EN (UK)": "Credit-sale",
     "EN (US)": "Credit-sale",
     "EN (IR)": "Credit sale",
     "FR": "Vente à crédit",
     "IT": "vendita a credito",
     "DE": "Verkauf auf Ziel",
     "CA": "venda a crèdit"
    },
    {
     "ES (ESP)": "Vivienda",
     "ES (ARG)": "Vivienda",
     "EN (UK)": "Home\/House Dwelling",
     "EN (US)": "Home\/House Dwelling",
     "EN (IR)": "Home\/House Dwelling",
     "FR": "Logement\/Maison\/Habitation",
     "IT": "abitazione",
     "DE": "Wohnung",
     "CA": "habitatge"
    }
   ]