import ContractDrafterComponent from "@/component/contractDrafter";
import TopImage from "@/component/topImage";

export default function ContractDrafterFR() {
  return  <>
  <TopImage
    name="Redactor de Documentos"
    description="Plantilla Francia"
    imageUrl="cabecera-contratos-inmocor.jpg"
  />

  <ContractDrafterComponent

title="COMPROMIS DE VENTE D'UN BIEN IMMOBILIER PROMESSE SYNALLAGMATIQUE DE VENTE D'UN BIEN IMMOBILIER"
        
    headersParts="ENTRE LES SOUSSIGNES:"
    parts="Monsieur/Madame XXX ( nom et prénom), né le XXX (date de naissance), de nationalité XXX, de demeurant XXX (adresse) à XXX (ville),OU :La société XXX (dénomination sociale), XXX (type de société) au capital de XXX euros ( capital social), immatriculée au RCS de XXX (ville) sous le XXX (numéro RCS), dont le siège social est situé XXX (adresse) à XXX (ville), prise en la personne de son représentant légal XXX (nom et fonction).Ci-après désigné sous le nom le « Vendeur »,ET :M. XXX (nom et prénom), né le XXX (date de naissance), de nationalité XXX de demeurant, XXX (adresse) à XXX (ville),OU :La société XXX (dénomination sociale), XXX (type de société) au capital de XXX euros ( capital social), immatriculée au RCS de XXX (ville) sous le XXX (numéro RCS), dont le siège social est situé XXX (adresse) à XXX (ville), prise en la personne de son représentant légal XXX (nom et fonction).Ci-après désigné sous le nom l'« Acquéreur »,L'Acquéreur et le Vendeur étant ci après collectivement dénommées les « Parties »"
		headersClausesClient="IL A ETE CONVENU CE QUI SUIT :"
		clausesClient={[`Le Vendeur, en s'obligeant et en obligeant ses héritiers, co-indivisaires, ayants droits solidairement entre eux, fussent-ils mineurs ou incapables, et en tant que de besoin, en se portant fort de leur acceptation, ou s'il y a lieu, de celle de leur représentant légal, promet de vendre à l'Acquéreur, dans les conditions et dans le délai indiqués ci-après, le bien et droits portant sur ce bien, dont la désignation suit.L'Acquéreur s'engage à acquérir, tant pour lui-même que pour toutes personnes cessionnaires ou substituées éventuelles dont il restera garant et solidaire, l'immeuble dont la désignation suit.`]}
    headersClausesContract='CLAUSES'
    clausesContract={[`ARTICLE 1 er :DESIGNATION DU BIENLe terme « l'Immeuble » désigne l'ensemble immobilier ci-après décrit ainsi que les Immeubles par destination qui en dépendent et qui constituent la propriété immobilière du Vendeur.Décrire précisément le bien objet du compromis en indiquant :-sa situation cadastrale et géographique (adresse et cadastre) XXX -sa situation locative au jour de la promesse et au jour de sa délivrance (libre de toute occupation locative ou par le Vendeur)-copropriété ou non : XXX-superficie : XXX-destination : XXX-particularités : XXX -Situation de l'Immeuble concernant la réglementation (diagnostic amiante, électricité, gaz, risques naturels et technologiques, termites, sinistres...) + joindre les justificatifs : XXX`,`
    ARTICLE 2 : DECLARATIONSLes Parties déclarent ne pas être concernées par une procédure de sauvegarde, de redressement ou de liquidation judiciaire, ni être en état de tutelle, curatelle, sous sauvegarde de justice, ou toute autre interdiction de faire des actes de disposition.L'Acquéreur déclare bien connaître le bien immobilier sus visé pour l'avoir visité et reconnaît l'exactitude des informations de l'article 1 er.Le Vendeur déclare que le bien est libre de toute hypothèque au jour des présentes et s'interdit de l'hypothéquer ou de l'aliéner pendant toute la durée de validité des présentes.Le Vendeur déclare qu'il n'a connaissance d'aucun acte tendant à l'expropriation de l'Immeuble, objet des présentes, et qu'il n'existe sur ce bien aucune injonction de travaux, arrêté de péril, insalubrité ou interdiction d'habiter.Le Vendeur s'interdit de conférer aucun droit réel ni personnel, ni charge quelconque sur l'Immeuble à vendre, de consentir aucun bail, location ou prorogation de bail, ou d'y apporter aucun changement sauf avec le consentement de l'Acquéreur.Les Parties déclarent qu'elles ont les capacités juridiques et financières permettant de réaliser les présentes.Rappel :Le Vendeur ne doit effectuer aucun acte qui pourrait faire obstacle à la vente. En cas de non respect de la promesse, le Vendeur engage sa responsabilité contractuelle, et peut avoir à verser des dommages et intérêts à l'Acquéreur. Si le Vendeur vend son bien à une autre personne pendant la période de validité de la promesse faite à l'Acquéreur, l'Acquéreur ne pourra pas demander l'annulation de la vente ainsi conclue mais seulement réclamer des dommages et intérêts au Vendeur.`,`
    ARTICLE 3 : ORIGINE DE PROPRIETE DU BIENLe Vendeur déclare être propriétaire de l'Immeuble et des droits s'y rattachant et les avoir acquis entre lesmains de XXX (vendeur initial) le XXX (date), par acte notarié dressé parMaître XXX ( notaire) en son étude située XXX ( adresse).Ladite mutation a été publiée au bureau des hypothèquesde XXX le XXX volume XXX numéro XXX`,`
    ARTICLE 4 : TRANSFERT DE PROPRIETE ET JOUISSANCELe transfert de la jouissance, des risques et de la propriété de l'Immeuble au Acquéreur est subordonné aux conditions suivantes :-la réalisation des conditions suspensives ci-après stipulées -la passation de l'acte authentique de réitération lequel devra être conclu dans les quinze jours/un mois/autre délai à convenir qui suivront la réalisation, dans le délai ci-après indiqué, de la dernière des conditions suspensives accompagnée du versement préalable du prix et des frais et loyaux coûts du contrat, qui sera dressé en l'étude de Maître _________ ( nom), notaire à _________ ( lieu) désigné dès à présent pour la rédaction dudit acte.Modifiez ou ajoutez toute condition supplémentaire à laquelle vous souhaitez soumettre le compromis de vente en détaillant et précisant toute formalité à accomplir.Si la vente devient parfaite par la réalisation des conditions suivantes, la jouissance du bien vendu sera transférée à l'Acquéreur le jour où l'acte authentique de réitération sera signé, par la prise de possession réelle de l'Immeuble.A défaut de réitération par acte authentique, un procès verbal de carence sera dressé à la requête de la partie la plus diligente à laquelle il appartiendra alors de se pourvoir en justice aux fins de réaliser ou faire réaliser ladite mutation.`,`
    ARTICLE 5 : CHARGES ET CONDITIONS DE LA VENTEEn cas de réalisation définitive de la vente, l'Acquéreur devra se soumettre aux charges et conditions applicables en matière de vente immobilière, et notamment aux conditions suivantes :- il sera subrogé dans tous les droi ts et obligations du Vendeur relatifs à l'Immeuble ; -il prendra les b iens et droits vendus, dans l'état où ils se trouveront au jour de la levée de l'option, qu'il soit bon ou mauvais ; -il supportera les serv itudes passives et profitera des servitudes actives, s'il en existe, à ses risques et périls, et renonce à tout recours contre le Vendeur concernant les servitudes affectant le bien au jour de l'entrée en jouissance. En aucun cas, le Vendeur ne pourra donc souffrir de recours quant aux modalités d'exercice desdites servitudes.OPTIONNELLe Vendeur déclare expressément qu'il n'a personnellement créé aucune servitude et qu'à sa connaissance, il n'existe au jour des présentes, aucune servitude affectant le bien.OU :Le Vendeur déclare expressément qu'il n'a personnellement créé aucune servitude et qu'à sa connaissance, il n'existe au jour des présentes, aucune autre servitude affectant le bien que celles qui peuvent résulter de la situation naturelle des lieux, des titres et pièces en sa possession. Concernant l'Immeuble, objet des présentes, sont à répertorier 
    les servitudes suivantes (par exemple) :1.Réglementation d'urbanisme applicable dans la commune dont dépend ledit Immeuble et dont le Acquéreur reconnaît avoir pris connaissance préalablement à la signature des p résentes : les lister2.Servitudes légales : les lister3.Servitudes résultant de la natu re et de la situation des lieux : les lister4.Titres existants et joints aux présentes : les listerLe Vendeur s'engage, jusqu'à la réitération par acte authentique à ne faire aucun acte ayant pour conséquences d'aggraver les servitudes existantes au jour du présent compromis.-il acquittera, à compter de l'entrée en jouissance, les impôts, contributions et charges de toute nature, auxquels l'Immeuble est et pourra être assujetti ; -il se chargera de procéder à la résiliation des contrats d'assurance souscrits par le Vendeur, s'il y a lieu, ou d'en assurer la continuation en mettant en oeuvre les procédures utiles à l'une ou l'autre de ces situations.OU (si vous décidez que c'est au Vendeur de se charger des contrats d'assurance)Le Vendeur se chargera de procéder à la résiliation des contrats d'assurance portant sur l'Immeuble, avant l'entrée en jouissance de l'Acquéreur.ATTENTION : Les clauses de renonciation à toute action portant sur les vices du bien vendu (vices cachés, lésion...) sont réputées non écrites : Si la promesse mentionne que l'Acquéreur ne peut pas se prévaloir des vices de la chose, apparents ou cachés, ou de la lésion concernant la superficie de l'Immeuble, la clause n'a aucune valeur et l'Acquéreur de l'Immeuble pourra tout de même engager une action fondée sur les vices de la chose vendue.`,`
    ARTICLE 6 : CONDITIONS SUSPENSIVESLa présente promesse est consentie par le Vendeur et acceptée par l'Acquéreur sous réserve de la réalisation des évènements suivants au plus tard le XXX ( ce sont des exemples, vous pouvez donc y ajouter toute condition suspensive conventionnelle de votre choix) :-que le certificat d'urbanisme ne révèle aucune servitude ou emprise administrative de nature à compromettre gravement les droits de l'Acquéreur OU :-que la note de renseignement d'urbanisme concernant l'Immeuble, objet des présentes, produite à l'initiative du Vendeur, ne révèle aucune injonction de travaux, ni état de péril ou insalubrité, ni servitude ou autre empêchement susceptible de réduire sensiblement la valeur vénale de l'Immeuble ou son usage normal.-que les biens objet de la présente ne s e trouvent grevés, au jour de l'entrée en jouissance, d'aucune inscription ou privilège qui soit d'un montant supérieur au prix de vente convenu au jour des présentes, selon les renseignements hypothécaires de l'Immeuble produits à l'initiative du VendeurOU :-que les biens objet de la présente ne s e trouvent grevés, au jour de l'entrée en jouissance, d'aucune inscription ou privilège, selon les renseignements hypothécaires de l'Immeuble produits à l'initiative du Vendeur-que le Vendeur fasse son affaire, dans les plus brefs délais, de la purge de tout droit de préemption portant sur l'Immeuble-que l'Acquéreur obtienne le ou les prêts sollicités pour financer le coût global de son acquisition éventuelle, dont les caractéristiques et conditions sont décrites à l'article 9.La réalisation des conditions susvisées n'entraînera pas le transfert de la propriété de l'Immeuble, objet des présentes, lequel est subordonné à la réitération par acte authentique en l'étude de Maître XXX tel que mentionné à l'article 4 des présentes.`,`
    ARTICLE 7 : VERSEMENT D'UN ACCOMPTEEn considération des présentes et à titre d'indemnité forfaitaire pour le préjudice du Promettant résultant de l'immobilisation de l'Immeuble, un acompte de XXX % du prix de vente, soit XXX ( somme en lettres) Euros (somme en chiffres entre parenthèses) sera versé au Vendeur dès la signature des présentes par l'Acquéreur.OPTIONNELD'un commun accord, les Parties conviennent de remettre ladite indemnité d'immobilisation à Monsieur XXX, ayant la qualité de tiers constitué séquestre. Le séquestre sera déchargé de cette mission, soit par les Parties, d'un commun accord, qui préciseront alors la destination des fonds, ou, soit, à défaut, par décision de Justice. Monsieur XXX (nom), XXX (profession), domicilié à XXX (adresse) déclare :-qu'il exerce son activité à l'adresse sus indiquée ;-qu'il est garanti par XXX ( Nom et adresse du garant) pour un montant de XXX euros ;-qu'il est titulaire de XXX ( carte professionnelle, mandat... + leurs numéros)M.XXX accepte la mission de séquestre et reconnaît avoir reçu de l'Acquéreur ladite somme de XXX (somme en lettres) Euros (somme en chiffres entre parenthèses), sous forme d'un chèque numéro XXX en date du XXX émis à l'ordre de XXX L'Acquéreur déclare qu'il lui a été remis, en contrepartie de la somme séquestrée, un reçu par le séquestre. Le Vendeur déclare qu'il lui a été remis le duplicata du reçu par le séquestre.Si la vente se réalise, Monsieur XXX versera cette indemnité d'immobilisation entre les mains de Maître XXX lors de la réitération de la présente promesse, afin d'en permettre l'imputation sur le prix de vente.En cas de caducité du présent compromis, par suite de la défaillance ou de la non-réalisation de l'une des conditions suspensives, l'acompte devra être restitué par le Vendeur/par le séquestre à l'Acquéreur dans un délai de ____ jours, sans retenue ni pénalité d'aucune sorte.L'acompte demeurera néanmoins acquis de plein droit et sans formalité au Vendeur, à titre de dommages et intérêts, si l'Acquéreur refuse de réitérer la vente en signant l'acte authentique, alors que toutes les conditions suspensives sont réalisées dans le délai ci-après fixé et selon les conditions indiquées aux présentes.`,`
    ARTICLE 8 : PRIXLa vente, si elle se réalise, aura lieu moyennant le prix principal de XXX euros ( somme en lettres) Euros (somme en chiffres entre parenthèses), net de toute commission, payable comptant au jour de la signature de l'acte authentique de vente.L'Acquéreur devra payer au plus tard le jour de la signature de l'acte authentique de vente, le prix de vente, ainsi que les frais, droits et honoraires de l'acte authentique. Le montant lui en sera indiqué par Maître ________________. À défaut, le transfert de propriété ne pourra s'effectuer malgré la demande de réalisation.Conformément à l'article 7 des présentes, le séquestre remettra entre les mains de Maître XXX le jour de la réitération de la vente par acte authentique, le montant de l'indemnité d'immobilisation séquestrée qui viendra donc s'imputer sur le prix de vente.OUSi la vente se réalise, l'acompte versé lors de la conclusion du présent compromis viendra s'imputer sur le prix de vente et sera donc déduite du prix principal mentionné ci-dessus.`,`
    ARTICLE 9 : FINANCEMENT DU BIENL'Acquéreur déclare, que pour financer le coût global de l'acquisition de l'Immeuble, il utilisera ses denierspersonnels ou assimilés, sans recours à un prêt, ou au concours de tout établissement de crédit. Ainsi, l'Acquéreur recopiera de sa main la mention suivante : « Je soussigné XXX déclare ne recourir à aucun prêt pour l'acquisition du bien immobilier, objet des présentes. Si, par la suite, je déclare recourir à un prêt, je ne pourrai me prévaloir des dispositions des articles L 312-1 et suivants du code de la consommation ».OU :L'Acquéreur déclare, que pour financer le coût global de l'acquisition de l'Immeuble, il sollicitera le concours d'un ou plusieurs établissements de crédit. Il lui sera en effet nécessaire d'obtenir un prêt d'un montant au moins égal à __________ (somme en lettres) Euros (somme en chiffres entre parenthèses).Par conséquent, la présente promesse est soumise à la condition suspensive de l'obtention du ou des prêts qui seront sollicités par l'Acquéreur.Le ou lesdits prêts devront présenter les caractéristiques suivantes (précisez les caractéristiques) :-montant-nature-garanties et sûretés-Périodicité du remboursement-Taux d'intérêts-Etablissements de prêts sollicitésL'Acquéreur s'engage à mener les procédures nécessaires à l'obtention du ou desdits prêts afin de permettre la réalisation de la vente, à savoir adresser les dossiers, pièces, documents, attestations, certificats et renseignements utiles aux établissements de crédits auprès desquels seront sollicités ces prêts.La présente condition suspensive sera réputée réalisée dès la présentation par le ou les établissements de crédit sollicités d'une ou plusieurs offres régulières correspondant aux caractéristiques décrites ci-dessus, et après l'agrément du ou des assureurs, en cas d'adhésion obligatoire à un contrat d'assurance collective lié à ces prêts. Cette acceptation ne pourra intervenir que dix jours après la réception des offres et devra être donnée par lettre, le cachet de la poste faisant foi.Si l'Acquéreur entend renoncer, pour des raisons de pure convenance personnelle, à la condition suspensive d'obtention d'un prêt pour l'acquisition de l'Immeuble, il devra le notifier au Vendeur par lettre recommandée avec avis de réception, acte extra judiciaire ou remise en main propre contre récépissé. 
    La notification devra alors obligatoirement comporter, de façon manuscrite, la mention suivante, conformément à l'article L. 312-17 du Code de la consommation : « Je soussigné ______________ déclare ne recourir à aucun prêt pour l'acquisition du bien immobilier, objet des présentes. Si, par la suite, je déclare recourir à un prêt, je ne pourrai me prévaloir des dispositions des articles L 312-1 et suivants du code de la consommation ».`,`
    ARTICLE 10 : FRAIS, IMPOTS ET TAXESTous les frais, coûts et droits afférents au présent acte sont à la charge de L'Acquéreur, de même que les frais, coûts et droits afférents à l'acte de réitération et ceux qui en seront la suite ou la conséquence.Toutefois, les frais sus évoqués seront supportés par le Vendeur en cas de non réalisation de la vente provenant de son fait.`,`
    ARTICLE 11 : ELECTION DE DOMICILEPour l'exécution des présentes et de leur suite, les Parties font élection de domicile en leurs demeures respectives.`]}
    footer="Fait à XXX (lieu), le XXX (date). En XXX exemplaires originaux, dont un pour chacune des Parties, un pour l'enregistrement (ajouter le cas échéant : et un pour le séquestre).Ajouter éventuellement la mention manuscrite de l'article L. 312-17 du code de la consommation (lorsque l'achat se fera sans prêt) « Je soussigné XXX déclare ne recourir à aucun prêt pour l'acquisition du bien immobilier, objet des présentes. Si, par la suite, je déclare recourir à un prêt, je ne pourrai me prévaloir des dispositions des articles L 312-1 et suivants du code de la consommation »"
    clausesAdd = "CLAUSES ADDITIONNELLES"
    seller="Vendeur"
    buyer="Acheteur"
  />
</>;
}
